Primera version de FAQ para BQAC
Laboratoria/curriculum pull request #1457
Opened 2023-07-17 20:46 UTC by ssinuco

Para solucionar #1456

2023-07-20 17:07 UTC, mfdebian submitted a review, later dismissed
Mil gracias querido @ssinuco

Sólo propongo una pequeña modificación, y me queda la duda de cómo hacemos para la versión en português del FAQ, me imagino que deberíamos pedirle a alguna coach de Brasil que pueda hacer una versión en português de los videos, no? qué opinan?

Además, como conversamos en nuestro último weekly, los archivos tipo `FAQ.md` deberían ir dentro de un directorio `docs/`

2023-07-20 17:07 UTC, mfdebian commented on projects/04-burger-queen-api-client/FAQ.md
> +Última actualización: 13 de julio de 2023
```suggestion

```

Personalmente le quitaría esta línea, creo que es algo que de cara a las estudiantes nos puede llegar a jugar más en contra que a favor en un mediano plazo, y en caso que alguien del equipo necesite tener esa info, puede simplemente consultar su historia aquí en Github.

2023-07-20 17:07 UTC, mfdebian commented on projects/04-burger-queen-api-client/FAQ.md
No he tenido chance de revisar todos los videos, pero confío 100% en tu criterio @ssinuco GRACIAS! :pray:

2023-07-20 22:11 UTC, unjust requested changes

2023-07-20 22:11 UTC, unjust commented on projects/04-burger-queen-api-client/README.md
> +Consulta los [FAQ](./FAQ.md) o súmate al canal de Slack
Yo pondria el `FAQ.md` dentro de `/docs`

2023-07-20 22:11 UTC, unjust commented on projects/04-burger-queen-api-client/README.pt.md
> +Consulte as [FAQ](./FAQ.md)
tenemos FAQ en portugues?

2023-07-31 22:27 UTC, ssinuco commented
Ya agregué todas sus sugerencias. Solo falta la traduccion en portugués. Tendriamos que pedirle a una coach de Brazil que nos ayude con eso o subir los videos , revisar si youtube crea los subtitulos y sugerirle a las estudiantes que los activen en portugues? Esto es una posibilidad pero en relaidad queria que se quedara como links al canal de slack para justamente incentivar su uso.

2023-08-08 19:29 UTC, mfdebian reviewed
Mil gracias @ssinuco :partying_face: 

Para estar al día, entonces, arreglando los issues del `md-lint` para que pase los test, lo único que faltaría es que una coach de brasil pueda aprobar que los subtítulos auto-generados estén okey, no? Con eso ya estaríamos :hugs:

2023-08-11 19:43 UTC, paclaraujo commented on projects/04-burger-queen-api-client/docs/FAQ.pt.md
> +- Como posso criar um aplicativo React?
```suggestion
- Como posso criar um projeto React?
```

2023-08-11 19:43 UTC, paclaraujo commented on projects/04-burger-queen-api-client/docs/FAQ.pt.md
> +- Como posso criar um aplicativo Angular?
```suggestion
- Como posso criar um projeto em Angular?
```

2023-08-11 19:43 UTC, paclaraujo commented on projects/04-burger-queen-api-client/docs/FAQ.pt.md
> +- O que são headers, body, verbos, códigos e codificações de uma requisição HTTP?
```suggestion
- O que são headers, body, verbos, códigos e encodings de uma requisição HTTP?
```

2023-08-11 19:43 UTC, paclaraujo commented on projects/04-burger-queen-api-client/docs/FAQ.pt.md
> +- Como posso implantar a API Mock?
```suggestion
- Como posso implementar a API Mock?
```

2023-08-11 19:43 UTC, paclaraujo commented on projects/04-burger-queen-api-client/docs/FAQ.pt.md
> +- Eu quero fazer as validações para que meu login navegue para
```suggestion
- Quero fazer as validações para que meu login navegue para
```

2023-08-11 19:43 UTC, paclaraujo commented on projects/04-burger-queen-api-client/docs/FAQ.pt.md
> +_Remarque : certaines vidéos sont en anglais, mais vous pouvez activer
Porém, a tradução automática não está fazendo sentido.

2023-08-18 19:28 UTC, mfdebian commented
muito obrigado pelo seu review @paclaraujo :blush: :yellow_heart:

2024-02-16 15:24 UTC, unjust commented on projects/04-burger-queen-api-client/README.pt.md
> +Consulte o [FAQ](./docs/FAQ.pt.md)
```suggestion
Consulte o [FAQ](./docs/FAQ.md)
```

2024-02-16 15:27 UTC, unjust commented on projects/04-burger-queen-api-client/README.pt.md
> +Consulte o [FAQ](./docs/FAQ.pt.md)
cuando renderizamos los docs de traduccion, el proceso quita los extensiones de idiomas

2024-02-16 15:30 UTC, unjust reviewed
Algunas comentarios para los nombres de links, puede hacer los mismos cambios en pt porfavor?

2024-02-16 15:30 UTC, unjust commented on projects/04-burger-queen-api-client/docs/FAQ.md
> +  [video](https://youtu.be/PSltMw_3pjg)
```suggestion
  [video sobre React](https://youtu.be/PSltMw_3pjg)
```
mas accessible, los nombres de links en un doc puede ser distinguible de otros "video" links

2024-02-16 15:30 UTC, unjust commented on projects/04-burger-queen-api-client/docs/FAQ.md
> +  [video](https://youtu.be/mASkp0886QY)
```suggestion
  [video sobre Angular](https://youtu.be/mASkp0886QY)
```

2024-02-16 15:30 UTC, unjust commented on projects/04-burger-queen-api-client/docs/FAQ.md
> +  Puedes consultar el siguiente [video](https://youtu.be/hyK8TeimrJc).
```suggestion
  Puedes consultar el siguiente [video sobre API Mock](https://youtu.be/hyK8TeimrJc).
```

2024-02-16 15:30 UTC, unjust commented on projects/04-burger-queen-api-client/docs/FAQ.md
> +  Puedes consultar el siguiente [video](https://youtu.be/f4urqhsMw5k).
```suggestion
  Puedes consultar el siguiente [video sobre HTTP](https://youtu.be/f4urqhsMw5k).
```

2024-02-16 15:30 UTC, unjust commented on projects/04-burger-queen-api-client/docs/FAQ.md
> +  [video](https://youtu.be/Z0wHRu2n7Cg)
```suggestion
  [video sobre usuarias](https://youtu.be/Z0wHRu2n7Cg)
```

2024-02-20 00:01 UTC, unjust approved these changes
🙌

2024-02-20 03:05 UTC, merged