feat: add some java learning objectives to data.yml
Laboratoria/curriculum pull request #1525
Opened 2023-08-14 21:58 UTC by NaraSakamoto

2023-08-15 07:30 UTC, merunga commented on learning-objectives/data.yml
> +  - recursion
`recursion` lo quitaría

2023-08-17 17:38 UTC, NaraSakamoto commented
> Hola @NaraSakamoto cual issue esta cerrando en el PR? Puedes mencionarlo en la descripcion por favor?

Feito @unjust

2023-08-17 17:49 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +  - stream
@merunga eu acredito que sim! Mas vou perguntar pra comunidade e coletar mais opiniões! Quem sabe nos ajuda a pensar melhor sobre isso!

2023-08-17 17:51 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +    - hashmap
Podemos sim! Acho uma boa!

2023-08-17 17:55 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +  - stream
Algumas respostas: 

"Oii gente entrando um pouco nesse debate das funções lambdas, acho legal a pessoa junior já se familiarizando com essas funções sim, não como uma exigência logo de cara, mas conhecer a utilidade e não se confundir quando for se deparar com um código como esse em um sistema já existente e pode precisar dar alguma manutenção e tal" de Carol Maia

"Minha visão é dependendo do time vai ter muito stream e lambda e daí o Júnior vai penar pra entender o código que ta mexendo. Ensinaria o optional pq o Spring devolve muita coisa agora com optional e se for cair na parte do spring data teria que lidar com isso" de Paula Santana

"Acredito que optional sim... o restante pelo menos o inicial... pq stream pode ficar bem avançado" de Anni Carol

2023-08-21 15:47 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +
@merunga Adicionei algumas OAs para Hibernate. Não trabalhei profundamente nisso.. adicionei o que lembrei. rs. 

---

Se agregaron algunos OA para Hibernate. No trabajé profundamente en eso... Agregué lo que recordaba.

2023-08-24 08:31 UTC, merunga commented on learning-objectives/data.yml
> +  - spring-security
spring
```suggestion
spring:
  - core-concepts:
    - beans
    - inversion-of-control
    - annotations
  - spring-boot:
    - servlets
    - controllers
    - services
  - spring-data-jpa:
    - entities
    - repository
  - setup:
    - initializr
    - gradle
```
@NaraSakamoto que te parece esto?
spring-security no lo estamos contemplando

@NaraSakamoto O que você acha disso?
Não estamos contemplando spring-security

2023-08-24 09:06 UTC, merunga commented on learning-objectives/data.yml
> +      - polimorphism
composition?

2023-08-24 09:08 UTC, merunga commented on learning-objectives/data.yml
> +      - polimorphism
Tiene sentido todavia hablar de SOLID Principles?

Ainda faz sentido falar sobre  SOLID PRinciples?

@NaraSakamoto @ssinuco

2023-08-24 09:36 UTC, merunga commented on learning-objectives/data.yml
> +  - stream
@NaraSakamoto en algun lugar deberiamos agregar `uml-class-diagram`

2023-08-25 21:12 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +  - stream
@merunga será que dentro de object-oriented ?

2023-08-25 21:15 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +  - spring-security
@merunga Gostei das sugestões! Faz muito sentido o core-concepts. Tenho dúvidas somente sobre servlets. Acho que nunca cheguei a usar com o spring-boot! Será que é algo mais recente?  Acho que valeria adicionar componets, também! Junto de services e controllers são annotations muito utilizadas.

2023-08-25 21:16 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +      - polimorphism
@merunga @ssinuco Faz sentido sim, porém acho que para pessoas iniciantes talvez seja um conceito um pouco mais avançado.

2023-08-25 21:41 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +  - spring-boot-starter-test:
@merunga adicionei algumas OAs sobre testes. 

---

@merunga agregó algunos OA sobre las pruebas.

2023-08-25 21:41 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +  - spring-web:
@merunga add sobre web. 

--- 

@merunga agregó algunos OA sobre web.

2023-08-25 21:43 UTC, NaraSakamoto commented on learning-objectives/data.yml
> +  - testing:
@merunga add sobre testes aqui também

---

@merunga agregado sobre pruebas aquí también

2023-08-28 05:27 UTC, merunga commented on learning-objectives/data.yml
> +    - mock-bean
Buenisimo @NaraSakamoto! Ese starter usa Junit, Hamcrest y Mockito. Ponemos eso en lugar de estos?

---

Excelente @NaraSakamoto! Esse starter usa Junit, Hamcrest e Mockito. Vamos colocá-los em seu lugar?

2023-08-30 02:19 UTC, vivieall commented on learning-objectives/data.yml
@NaraSakamoto  Haciendo una pruebita encontré un pequeño error en la identación, debería quedar / Fazendo um pequeno teste, encontrei um pequeno erro na indentação, deveria ser:
```
      - uml: 
        - class-diagram
        - abstraction
        - composition
        - interface
        - polymorphism
```

2023-08-30 05:15 UTC, merunga commented on learning-objectives/data.yml
@vivieall creo q está bien la indentación. De uml solo veríamos class-diagram, abstracion, composition, interface y polymorphism, son parte de OOP, no se uml

2023-08-30 05:15 UTC, merunga commented on learning-objectives/data.yml
> +  - object-oriented:
- object-oriented-programming

2023-08-30 05:16 UTC, merunga commented on learning-objectives/data.yml
> +  - object-oriented:
```suggestion
  - - object-oriented-programming:
```

2023-08-30 05:16 UTC, merunga commented on learning-objectives/data.yml
> +      - polimorphism
```suggestion
      - polymorphism
```

2023-08-31 13:10 UTC, NaraSakamoto commented on learning-objectives/data.yml
@vivieall desculpe pela demora para responder. Pensei como merunga disse mesmo! Vc concorda?
---
@vivieall perdón por la demora en responder. ¡Pensé que lo dijo Merunga! ¿Usted está de acuerdo?

2023-09-05 13:34 UTC, merunga requested changes
@NaraSakamoto los últimos cambios para mergear

2023-09-05 13:34 UTC, merunga commented on learning-objectives/data.yml
> +css:We’ll start by writing a very simple JUnit 5 test, but instead of using JUnit’s assertEquals methods, we use Hamcrest’s assertThat construct and the standard set of matchers, both of which we sta
```suggestion
css:
```
@NaraSakamoto esto se agregó por error, no?

2023-09-05 13:34 UTC, merunga commented on learning-objectives/data.yml
> +  - stream
si!

2023-09-05 14:58 UTC, merunga submitted a review, later dismissed

2024-01-03 18:08 UTC, unjust commented
esta trabajo a esta.

2024-01-03 18:08 UTC, closed without merging