README inicial del proyecto "Guess the Number" - JAVA
Laboratoria/curriculum pull request #1532
Opened 2023-08-21 22:27 UTC by vivieall

Este PR draft introduce el proyecto "Guess the Number - Adivina el número", un juego interactivo diseñado para ayudar a las estudiantes a familiarizarse con Java y la programación orientada a objetos. En este borrador, se proporciona una descripción general del proyecto, incluyendo su propósito y cómo se juega. También se detallan las consideraciones generales y técnicas para la implementación del juego.  _**Los objetivos de aprendizaje aún están pendientes de agregar.**_ 

El borrador incluye la estructura del índice y una descripción detallada de las clases propuestas para el juego, como GameLogic, Player y Computer, así como sus propósitos y métodos. Además, se presentan los criterios mínimos de aceptación del proyecto, que resumen lo que se espera lograr con el juego.

Este PR draft se crea para fomentar la colaboración y la revisión temprana de las ideas y la estructura del proyecto. ¡Espero sus comentarios y sugerencias para asegurarnos de que el proyecto siga en la dirección correcta!

PD. Commit respondiendo al[ issue 1500](https://github.com/Laboratoria/bootcamp/issues/1501)

2023-08-24 09:13 UTC, merunga commented
@vivieall asegurate porfa de ejecutar `npm run mdlint` para asegurarte que el markdown cumpla con el formato necesario

2023-08-24 09:33 UTC, merunga requested changes

2023-08-29 08:04 UTC, merunga commented on projects/XX-guess-the-number/image.png
la imagen debería se agnóstica de lenguaje de programación... quizás querramos usar el mismo proyecto para otro stack

2023-08-30 01:43 UTC, vivieall commented on projects/XX-guess-the-number/image.png
¡Claro! Toda la razón, lo actualicé por el de aquí que está genérico: 
![image](https://github.com/Laboratoria/bootcamp/assets/13903491/1f7e09b1-6f47-4796-9f6b-61d994f87b16)

¿qué les parece?

2023-08-30 01:44 UTC, vivieall commented on projects/XX-guess-the-number/README.md
> +- El juego terminará cuando se adivine el número.
Actualizado. [Última versión del README](https://github.com/vivieall/bootcamp/tree/feat/guess-the-number/projects/XX-guess-the-number)

2023-08-30 02:08 UTC, vivieall commented on projects/XX-guess-the-number/README.md
> +
¡Realizado! Unicamente me percaté que hay un pequeñito bug en la identación aquí:
```
      - uml: 
        - class-diagram
      - abstraction
      - composition
      - interface
      - polimorphism 
```

Del resto todo ok, lo probé en mi local con dichos OA's y script generándose correctamente!

2023-08-30 02:10 UTC, vivieall commented on projects/XX-guess-the-number/README.md
> +
y del inglés, que vendría a ser  _polymorphism_ .

2023-08-30 05:32 UTC, merunga commented on projects/XX-guess-the-number/project.yml
> +  - java/collections/list/arraylist
- java/testing/junit
- java/testing/mocks

2024-01-03 18:02 UTC, unjust commented
GUess the Number ya esta en la curricula

2024-01-03 18:02 UTC, closed without merging