Define Movie Challenge Scope
Laboratoria/curriculum pull request #1546
Opened 2023-08-28 21:28 UTC by ssinuco

Para resolver #1544

2023-08-29 14:35 UTC, unjust reviewed
Me gusta la idea.
Creo necesitamos ordenar un poco de consideraciones en consideraciones técnica.
También pensar en que sería la vista principal o "vista catálogo". No se si podemos recomendar top 20 o de algún género en particular - para que la vista inicial no es tan general y quizás ellas pueden tener una "marca" o app distinta. Tipo los mejores de horror, o todo 80s etc.

2023-08-29 14:35 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +## 4. Consideraciones generales
Algunas de esos consideraciones son más técnica, puedes mover e partes de typescript frameworks y api key a las consideraciones técnicas

2023-08-29 14:35 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +Yo como usuaria quiero visualizar en un tabla (filas y columnas) el catálogo de películas
Puede ser un poco difícil el catálogo. Creo necesita un punto para empezar como los estrenos, top 20, o de un género como clásicos horror o algo

2023-08-29 14:35 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +- Para cada película se debe mostrar: poster, título original y año de lanzamiento.
Responsive

2023-08-29 14:35 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +- Los componentes desarrollados deben contar con test unitarios.
Y un code review ;-)

2023-08-29 14:35 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +- La aplicación cuenta con una paginación para explorar el catálogo por páginas.
Pagination esta bien pero quizá opcional?

2023-08-29 14:35 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +- Los componentes desarrollados deben contar con test unitarios.
Pull request, code review . O issue?

2023-08-29 14:35 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +Recuerda que si mockeaste la API, también tienes que desplegarla.
Cuando van a mockear?

2023-08-29 14:37 UTC, icarito requested changes
Me da pena perder el aspecto de "diseño de producto" que tenía este proyecto. Siempre hice énfasis en encontrar un "grupo objetivo" y animarlas a encontrar un nicho con una necesidad específica. Me gustaría conservar algo de ello.

2023-08-29 14:39 UTC, icarito commented on projects/05-movie-challenge-fw/README.md
> -estos datos y tenga una propuesta de valor atractiva para lxs usuarixs.
Me falta esto un poco. 

"construirás una _página web_ para **visualizar, filtrar y ordenar** el catálogo de películas" no me satisface tanto.

2023-08-31 20:38 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> -estos datos y tenga una propuesta de valor atractiva para lxs usuarixs.
y podemos decir "un catalogo de peliculas" pensando en su publico y usuaria

2023-08-31 20:41 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +- Para cada película se debe mostrar: poster, título original y año de lanzamiento.
Quiza abrimos eso un poco - se debe mostrar detalles de la pelicula - un poster y titulo al menos, con año, estrellas o director por ejemplo.

2023-08-31 20:43 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +- Se debe usar el _endpoint_
ahora entiendo que estamos dando un poco flexibilidad "with_genres" pero yo abriria eso un poco que usa el endpoint con al menos un param - genres, cast, origin country, release data para ellas pueden decidir para su usuaria.

2023-09-04 21:22 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +Recuerda que si mockeaste la API, también tienes que desplegarla.
Gracias por verlo, se me fue porque use BQAC como plantilla.

2023-09-04 21:26 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +## 4. Consideraciones generales
Agregue justo lo contrario. Que la aplicacion no debe ser responsive. El foco esta en React.

2023-09-04 21:27 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +- La aplicación cuenta con una paginación para explorar el catálogo por páginas.
Es obligatorio porque la API funciona con pagination

2023-09-04 21:27 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +- Para cada película se debe mostrar: poster, título original y año de lanzamiento.
Agregue justo lo contrario. Que la aplicacion no debe ser responsive. El foco esta en React.

2023-09-04 21:29 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +- Los componentes desarrollados deben contar con test unitarios.
@unjust no agregue Code Review por sugerencia de @merunga . No le hemos dado una guia a las estudiantes de como hacer un code review. No sabemos si esta pasando. No sabemos si las esta atrasando. 

En este caso la usabilidad tampcoo es el foco, es un tiempo que pueden usar enfocandose en react. Tampoco creo que hemos dado una guia a las estudiantes de como hacer un test de usabilidad.

2023-09-04 21:30 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +- Los componentes desarrollados deben contar con test unitarios.
En este caso la usabilidad tampcoo es el foco, es un tiempo que pueden usar enfocandose en react. Tampoco creo que hemos dado una guia a las estudiantes de como hacer un test de usabilidad.

2023-09-04 21:31 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> -estos datos y tenga una propuesta de valor atractiva para lxs usuarixs.
@icarito @unjust no se me ocurrio nada para incluir esto y no hacer que las estudiantes se desenfoquen en lo que realmente se busca que es que comprendan React. Las estudiantes puede "perder el tiempo" haciendo un prototipo de alta, haciendo un diseño responsive, haciendo pruebas de usabilidad...ahi ya se les fue uno o dos sprints.

2023-09-04 21:33 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +- Para cada película se debe mostrar: poster, título original y año de lanzamiento.
Agregue "Para cada película se debe mostrar **como mínimo**: poster, título original y año de lanzamiento."

2023-09-04 21:34 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +- Se debe usar el _endpoint_
Podrias validar si cerrarlo hace que las estudiantes termine este proyecto en menor tiempo y se lleven aprendizajes mas cosnolidados.

2023-09-05 15:04 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +- Se debe usar el _endpoint_
Y si ellas usan `discovery` endpoint con un `genre` en particular? Podemos decir este Hisotria de Usario es "Filtro por parametro (ejemplo género)" y decirles que debe filtrar por algun parametro por ejemplo genero..." porque si es una pagina de peliculas accion quiza tiene mas sentido si filtra por director.

2023-09-06 16:48 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +
si ya está en la seccion "5. Consideraciones técnicas"

2023-09-14 19:37 UTC, unjust reviewed
Algunas cambios de spelling, un sugerencia de texto para la tematica de Project

2023-09-14 19:37 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +filtrar y ordenar** el catálogo de películas de [_The Movie Database API V3_](https://developer.themoviedb.org/docs).
```suggestion
En este proyecto, crearás una página web destinada a visualizar, filtrar y
ordenar el catálogo de películas de [_The Movie Database API V3_](https://developer.themoviedb.org/docs).
Esta página puede servir como un catálogo de
películas general, pero también, si te animas,
puedes considerar la posibilidad de diseñarla
para un público y usuarias específicas
con preferencias como "películas western"
o "películas de las 80's" por ejemplo.
```

2023-09-14 19:37 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +filtrar y ordenar** el catálogo de películas de [_The Movie Database API V3_](https://developer.themoviedb.org/docs).
Aqui es una idea como podemos dejar un poco de pensamiento de usuaria, sin exigirlo.

2023-09-14 19:37 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +## 8. Pistas / Tips
```suggestion
## 9. Pistas, tips y lecturas complementarias
```

2023-09-14 19:37 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +### Explora la documentacion del framwork elegido
```suggestion
### Explora la documentacion del framework elegido
```

2023-09-14 19:37 UTC, unjust commented on projects/05-movie-challenge-fw/README.md
> +pasos independiente del framewok que uses:
```suggestion
pasos independiente del framework que uses:
```

2023-09-18 14:41 UTC, ssinuco commented on projects/05-movie-challenge-fw/README.md
> +filtrar y ordenar** el catálogo de películas de [_The Movie Database API V3_](https://developer.themoviedb.org/docs).
De acuerdo!

2023-09-19 01:58 UTC, unjust submitted a review, later dismissed
👍 Gracias @ssinuco . Los cambios me parecen genial.

2023-09-21 16:01 UTC, paclaraujo commented on projects/05-movie-challenge-fw/README.pt.md
> +implantar nossa aplicação web estática (HTML, CSS e JavaScript) e também
```suggestion
fazer deploy da nossa aplicação web estática (HTML, CSS e JavaScript) e também
```

2023-09-21 16:01 UTC, paclaraujo commented on projects/05-movie-challenge-fw/README.pt.md
> +permite implantar aplicativos da web que são executados no servidor (Node.js).
```suggestion
permite fazer deploy de aplicativos da web que são executados no servidor (Node.js).
```

2023-09-21 16:01 UTC, paclaraujo commented on projects/05-movie-challenge-fw/README.pt.md
> +plataforma de implantação que permite implantar nossa aplicação web estática
```suggestion
plataforma que permite fazer deploy da nossa aplicação web estática
```

2023-09-21 16:01 UTC, paclaraujo commented on projects/05-movie-challenge-fw/README.pt.md
> +(HTML, CSS e JavaScript) e também permite implantar aplicativos da web que são
```suggestion
(HTML, CSS e JavaScript) e também permite fazer deploy de aplicativos da web que são
```

2023-09-26 16:05 UTC, unjust approved these changes

2023-09-26 16:47 UTC, merged