Reemplazar create react app
Laboratoria/curriculum pull request #1555
Opened 2023-09-05 19:07 UTC by DeysiVergara

2023-09-06 21:55 UTC, ssinuco commented
El unico comentario seria no agregar el procedimiento para crear las apps porque eso puede cambiar con nuevos releases de vite.

2023-09-14 19:59 UTC, unjust requested changes
Si no estamos mencionando nada de Vite anteriormente, agregaria una descripcion despues del link de Vite deciendo que es la herramienta que recomendamos para bootstrap/crear su applicacion.

2023-09-14 19:59 UTC, unjust commented on projects/04-notes/README.md
> +* [vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
```suggestion
* [Vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
```

2023-09-18 15:15 UTC, ssinuco submitted a review, later dismissed
De acuerdo con los cambios.

2023-09-19 17:56 UTC, unjust commented on projects/05-social-network-fw/README.md
> +* [Vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
Vite - Estruturando o Teu Primeiro Projeto de Vite
version pt: https://pt.vitejs.dev/guide/#scaffolding-your-first-vite-project

2023-09-19 17:57 UTC, unjust commented on projects/04-notes/README.md
> +* [Vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
Vite - Monta tu primer proyecto Vite
https://es.vitejs.dev/guide/#monta-tu-primer-proyecto-vite

2023-09-19 18:26 UTC, DeysiVergara commented on projects/05-social-network-fw/README.md
> +* [Vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
Este tambien va en español, ni note ni social network con framework tiene readme en portugués.

2023-09-19 18:49 UTC, unjust approved these changes

2023-09-19 18:55 UTC, merged