Agregar data y AI prompting para dataverse
Laboratoria/curriculum pull request #1560
Opened 2023-09-06 19:46 UTC by Davichobits

2023-09-07 17:50 UTC, unjust requested changes

2023-09-07 17:50 UTC, unjust commented on projects/02-data-lovers/README.md
> +adecuará a lo que descubras que tu usuario necesita.
Pienso que construiras un apagina web debe ir primero, y despues 
"ademas, En este proyecto utilizarás herramientas de"...

que opinan?

2023-09-07 17:50 UTC, unjust commented on projects/02-data-lovers/README.md
> +filtrarla, ordenarla y hacer algún cálculo agregado**. Con cálculo agregado
```suggestion
filtrarla, ordenarla y y calcular alguna estadística**. Con estadística
```

2023-09-07 17:50 UTC, unjust commented on projects/02-data-lovers/README.md
> +   └── json.spec.js
ahora pienso que quitamos eso aqui y solo deja "tests-read-only"

2023-09-07 17:50 UTC, unjust commented on projects/02-data-lovers/README.md
> +  interfaz será desplegada usando [GitHub Pages](https://pages.github.com/).
Para ayudar con el orden, que estamos hablando de generacion de data aqui y el parte es mas abajo podemos

Idea 1:
- mover consideraciones generales antes de funcionalidades (entonces consideraciones generales, funcionalidades, consideraciones tecnicas)
- y linkear el "a la generación de la data" al seccion"Generar la data" abajo

Idea 2:
- sacar la seccion de Generar la data a su propio parte, antes de funcionalidades #3 Generacion de Data #4 Funcionalidades

2023-09-07 17:50 UTC, unjust commented on projects/02-data-lovers/README.md
> +#### Generar de la data
Hay que poner en un parte que el readme debe tener un screenshot o prueba de prompting si? QUiza podemos mencionarlo en este parte 
```
### Criterios del proyecto
#### Prueba de prompting o algo
```
y añadirlo a parte de checklist de project feedback abajo.

2023-09-07 19:32 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +adecuará a lo que descubras que tu usuario necesita.
Si, creo que el objetivo principal es la creación de la página web. El crear la data será algo adicional, e inclusive en algunos casos ya no será necesario si a la estudiante le está tomando mucho tiempo. Entonces me parece acertado la sugerencia.

2023-09-07 19:41 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +   └── json.spec.js
Y lo dejo dentro de la carpeta test entonces?

2023-09-07 19:45 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +  interfaz será desplegada usando [GitHub Pages](https://pages.github.com/).
Me gusta más la idea 1

2023-09-07 19:53 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +#### Generar de la data
@unjust  Te refieres a esto?

![image](https://github.com/Laboratoria/curriculum/assets/123121338/02f8a1c0-6ced-4eda-8150-eae05ca96bef)

Es lo que utilicé para generar la data de ejemplo

2023-09-07 20:00 UTC, kvnlab commented on projects/02-data-lovers/README.md
> +El proposito de generar la data en esta manera es brindarte la oportunidad de
```suggestion
El propósito de generar la data en esta manera es brindarte la oportunidad de
```

2023-09-07 20:46 UTC, unjust commented on projects/02-data-lovers/README.md
> +#### Generar de la data
Perdon me refiero que aggregamos el requisito para ellas de poner un screenshot de prompt 🙈 , pero no agregamos nosotros un screenshot.

2023-09-07 20:51 UTC, unjust requested changes

2023-09-07 20:51 UTC, unjust commented on projects/02-data-lovers/tests-read-only/json.spec.js
> +import jsonData from '../src/data/data.json'
no estoy segura que cuando corremos los tests que va a correr eso. hay que probar.
pero si pensamos que esta es una prueba del objetivo de data generada con prompting, quiza debemos que moverlo dentro de `tests-read-only/oas` y agregar un script al `package.json`

2023-09-08 13:41 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +#### Generar de la data
Lo voy a dejar como #### Prompt utilizado en el apartado ### Criterios del proyecto

2023-09-08 13:45 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +El proposito de generar la data en esta manera es brindarte la oportunidad de
Muchas gracias @kvnlab

2023-09-08 13:47 UTC, Davichobits commented on projects/02-data-lovers/tests-read-only/json.spec.js
> +import jsonData from '../src/data/data.json'
Buen punto, voy a probar

2023-09-08 14:06 UTC, merunga commented on projects/02-data-lovers/README.md
deberiamos proveer ademas versiones mobile, no?
promoveria un desarrollo mobile-first

2023-09-08 14:06 UTC, merunga commented on projects/02-data-lovers/README.md
> +    "description": "Primera programadora de la historia",
quizas es muy tarde y puede quedar para mas adelante, pero quizas estaria bueno poner restricciones sobre este texto, por ejemplo q tenga al menos 100 palabras y al menos 2 oraciones o algo asi. q opinan?
Creo q como esto va a ser el insumo para el chat en el futuro, mientras mas "contexto" se provea, creo q pueden haber resultados mas interesantes/divertidos.

2023-09-08 14:06 UTC, merunga commented on projects/02-data-lovers/tests-read-only/json.spec.js
> +import jsonData from '../src/data/data.json'
si de una, deberiamos tenermos en lugares diferentes

2023-09-08 20:06 UTC, unjust commented on projects/02-data-lovers/README.md
Ok. Agregamos wireframes para movil en otro issue.

2023-09-08 20:12 UTC, unjust commented on projects/02-data-lovers/README.md
> +    "description": "Primera programadora de la historia",
@Davichobits crees que es algo que podemos agregar aqui o prefieres en otro issue aparte?

2023-09-08 20:16 UTC, unjust reviewed
Algunas comentarios de @merunga que podemos hacer aca. Tenemos un poco tiempo hasta que necesitamos cerrar este PR y podemos avanzar con #1510.

2023-09-08 21:01 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +    "description": "Primera programadora de la historia",
Creo que si estamos a tiempo de hacer este cambio

2023-09-13 19:19 UTC, unjust commented
Estamos cerca, creo los pendientes serian:

- Actualizamos el readme y el json para usar un archivo `js` podemos nombrarlo `dataset.js`
- verificar que el tests de OAs corre, incluyendo lo de data
- Revisar que estamos consistente con las instrucciones de usar URLs de imagenes
- Revisar el feedback de Sergio en su pull https://github.com/Davichobits/curriculum/pull/2 para ver si hay algo mas que deberia cambiar
Falta algo?

2023-09-14 13:56 UTC, ssinuco reviewed
Algunas preguntas y comentarios

2023-09-14 13:56 UTC, ssinuco commented on projects/02-data-lovers/README.md
> +_conjunto (set) de datos_** generado anteriormente. Esta página web se
No veo que quede muy claro cuales son los "datos generado anteriormente"

2023-09-14 13:56 UTC, ssinuco commented on projects/02-data-lovers/README.md
> +como [ChatGPT](https://openai.com/chatgpt), [ExplainDev](https://explain.dev/),
¿ExplainDev se usa para generar un set de datos?

2023-09-14 13:56 UTC, ssinuco commented on projects/02-data-lovers/README.md
> +artificial, así como en tecnicas de
```suggestion
artificial, así como en técnicas de
```

2023-09-14 13:56 UTC, ssinuco reviewed
Algunas preguntas y comentarios

2023-09-14 15:07 UTC, unjust commented on projects/02-data-lovers/README.md
> +  herramienta basada en inteligencia artifical. Una vez generada la imagen,
No se que decidimos con @merunga . La ultima que escuchado es que no vamos a poner importancia a eso, pero pense quiza mal-entendi que ellas pueden buscar imagenes por su parte. Aun usan AI?

2023-09-14 15:09 UTC, unjust commented on projects/02-data-lovers/README.md
> +_conjunto (set) de datos_** generado anteriormente. Esta página web se
"que vas a generar con prompting."

2023-09-14 22:15 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +  se deberá agregar la URL en este campo.
No todos los servicios de generación de imágenes crean un URL pública, y si lo hacen es de pago. He visto algunas que te la dan la URL por tiempo limitado.

2023-09-14 22:20 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +  herramienta basada en inteligencia artifical. Una vez generada la imagen,
Si, este tema está en stand by. Pero creo que ya deberíamos reactivarlo porque necesitamos definir este punto. 
Se tiene estas dos propuestas: [huggingface](https://huggingface.co/spaces/laboratoria/dataverse-image-generation)
y [gencraft](https://gencraft.com/generate). Personalmente me gusta la segunda porque el resultado obtenido no es tan distorsionado como el que genera  huggingface

2023-09-15 00:47 UTC, ssinuco reviewed
Solo algunos pequeños detalles

2023-09-15 00:47 UTC, ssinuco commented on projects/02-data-lovers/README.md
>    Por ejemplo, la siguiente data correspondiente a pokemón Pikachu:
```suggestion
  Por ejemplo, la siguiente data correspondiente a Ada Lovelace:
```

2023-09-15 00:47 UTC, ssinuco commented on projects/02-data-lovers/README.md
> +|  |  └── data.json (La que hayas generado con la IA)
```suggestion
|  |  └── dataSet.js (La que hayas generado con la IA)
```

2023-09-15 00:47 UTC, ssinuco commented on projects/02-data-lovers/tests-read-only/json.spec.js
> +import jsonData from '../src/data/data.json'
```suggestion
import jsonData from '../src/data/dataSet.js'
```

2023-09-15 00:47 UTC, ssinuco commented on projects/02-data-lovers/README.md
> +  de la data completa (por ejemplo, promedio de personas nacidas en los años 80s).
```suggestion
  de la data completa (por ejemplo, total de personas nacidas en los años 80s).
```

2023-09-15 00:47 UTC, ssinuco commented on projects/02-data-lovers/README.md
> +  recomendamos utilizar los datos de ejemplo que los vas a encontrar en
```suggestion
  deberás utilizar los datos de ejemplo que los vas a encontrar en
```

2023-09-15 00:47 UTC, ssinuco commented on projects/02-data-lovers/README.md
> +* Si ves que te va a tomar más tiempo, te
```suggestion
* Si ves que te va a tomar más tiempo,
```

2023-09-15 00:48 UTC, ssinuco commented on projects/02-data-lovers/tests-read-only/json.spec.js
> +import jsonData from '../src/data/data.json'
No se si este cambio sugerido rompa las pruebas

2023-09-15 17:13 UTC, unjust commented on projects/02-data-lovers/README.md
> +  esta ruta: `./src/data/dataset.js`.
si quedamos con `dataset.js` cambiamos los referencias en todo `data.json` -> `dataset.js`

2023-09-15 17:14 UTC, unjust commented on projects/02-data-lovers/README.md
> +* [Wireframe mobile 1](https://github.com/Laboratoria/curriculum/assets/123121338/54711bb7-cb05-448e-b677-3cbd9bf13c14)
🤩 gracias por los wf mobile

2023-09-15 17:19 UTC, unjust commented on projects/02-data-lovers/README.md
> +  herramienta basada en inteligencia artifical. Una vez generada la imagen,
quiza recomendamos primero en `gencraft` entonces y segundo hugging face.
estamos linkeado hugging face con DALLE ? el espacio que recomienda @merunga  https://laboratoriala.slack.com/archives/C056FVCP1U1/p1694554717603339?thread_ts=1693343120.351459&cid=C056FVCP1U1

2023-09-15 17:29 UTC, unjust requested changes
consistencia con `dataset.js` y cambios en el test

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/README.md
> +|  |  └── dataSet.js (La que hayas generado con la IA)
```suggestion
|  |  └── dataset.js (La que hayas generado con la IA)
```

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +import jsonData from '../src/data/dataSet.js'
```suggestion
import data from '../src/data/dataset.js'
```

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +import jsonData from '../src/data/dataSet.js'
Tambien quiza renombrar el archivo `dataset.spec.js`

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +describe('JSON', ()=>{
```suggestion
describe('Tests de data set', ()=>{
```

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +  it('El archivo JSON debe ser un arreglo', ()=>{
```suggestion
  it('La data debe ser un arreglo', ()=>{
```

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +  it('El archivo JSON debe tener una longitud de 24 objetos', ()=>{
```suggestion
  it('El arreglo de data debe tener una longitud de 24 objetos', ()=>{
```

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +    expect(Array.isArray(jsonData)).toBe(true)
```suggestion
    expect(Array.isArray(data)).toBe(true)
```

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +    jsonData.forEach(item => {
```suggestion
    expect.assertions(data.length*4)
    data.forEach(item => {
```

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +    jsonData.forEach(item => {
```suggestion
    expect.assertions(jsonData.length*2)
    data.forEach(item => {
```

2023-09-15 17:29 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +    jsonData.forEach(item => {
```suggestion
    data.forEach(item => {
```

2023-09-15 17:40 UTC, unjust commented on projects/02-data-lovers/README.md
> +      - [ ] Historias de usuaria
El formato en esta parte en un poco roto https://github.com/Laboratoria/curriculum/blob/03e4f913ba46f70862e2f3b6dcb00fb1b2ba7002/projects/02-data-lovers/README.md#10-consideraciones-para-pedir-tu-project-feedback
Puedes arreglarlo?

2023-09-15 17:45 UTC, unjust commented on projects/02-data-lovers/tests-read-only/dataSet.spec.js
> +})
nombramos este archivo `oa-js-datatypes.spec.js` ?
y moverlo dentro un carpeta `tests-read-only/oa`

2023-09-18 15:38 UTC, merunga commented on projects/02-data-lovers/README.md
> +o [Hugginface](https://huggingface.co/spaces/laboratoria/dataverse-image-generation)
esto no se si deberiamos ponerlo aqui todavia, no hay ningun tipo de control de consumo

2023-09-18 15:38 UTC, merunga commented on projects/02-data-lovers/README.md
>  ##### Prototipo de baja fidelidad
esta seccion sigue teniendo sentido al darle los mockups?

2023-09-18 15:38 UTC, merunga commented on projects/02-data-lovers/README.md
>  #### Testeos de usabilidad
Esto sucede en la realidad? Tiene sentido al darles los mockups?

2023-09-18 15:38 UTC, merunga commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +  });
faltaria test sobre longitud de description

2023-09-18 15:38 UTC, merunga commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +  });
quizas otro para q img sea una URL

2023-09-18 15:38 UTC, merunga commented on projects/02-data-lovers/README.md
> +* `img:` URL de la imagen. Esta imagen será generada a través de alguna
Super tarde, pero quizas
```suggestion
* `imgSrc:` URL de la imagen. Esta imagen será generada a través de alguna
```

2023-09-18 17:22 UTC, unjust commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +  });
Ok tiene sentido. @Davichobits me avisas si pueden! O si no , creo un issue.

2023-09-18 19:46 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +#### Historias de usuaria
La verdad si. Podría dejar solamente para las "Historias de usuario" la terminación a "o" y para el resto si dejar como "la usuaria" @merunga

2023-09-18 20:04 UTC, Davichobits commented on projects/02-data-lovers/README.md
> +o [Hugginface](https://huggingface.co/spaces/laboratoria/dataverse-image-generation)
@unjust te refieres a no sugerirles que busquen en internet una herramienta generadora de imágenes si no que directamente usen la que proponemos?

2023-09-18 20:07 UTC, Davichobits commented on projects/02-data-lovers/README.md
>  ##### Prototipo de baja fidelidad
Los mockups que les proponemos son de referencia, a veces los toman pero mayormente proponen otros diseños.

2023-09-18 22:11 UTC, Davichobits commented on projects/02-data-lovers/README.md
>  #### Testeos de usabilidad
Yo diría que si, como mayormente ellas proponen su propio diseño, sería necesario el testeo de usabilidad.

2023-09-19 10:53 UTC, merunga commented on projects/02-data-lovers/README.md
> +o [Hugginface](https://huggingface.co/spaces/laboratoria/dataverse-image-generation)
Esta @Davichobits 
https://www.bing.com/create
Pruebala a ver q te parece y la agregamos en lugar de la nuestra de hugging face, inclusive antes de GenCraft la pondria.

2023-09-19 10:53 UTC, merunga commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +  it('El valor de la propiedad "name" debe ser un string', ()=>{
```
expect.assertions(data.length)
```

2023-09-19 10:53 UTC, merunga commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +  it('El valor de la propiedad "imgSrc" debe ser un string', ()=>{
```
expect.assertions(data.length)
```

2023-09-19 10:53 UTC, merunga commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +  it('La propiedad "imgSrc" debe contener una URL válida', () => {
```
expect.assertions(data.length)
```

2023-09-19 10:53 UTC, merunga commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +  it('El valor de la propiedad "statistics" debe ser un objeto', ()=>{
```
expect.assertions(data.length)
```

2023-09-19 10:53 UTC, merunga commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +  it('El valor de la propiedad "description" debe ser un string', ()=>{
```
expect.assertions(data.length)
```

2023-09-19 10:53 UTC, merunga commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +  it('El valor de la propiedad "description" debe tener al menos 100 palabras', ()=>{
```
expect.assertions(data.length)
```

2023-09-19 10:53 UTC, merunga commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +      }
Esto sientes q hace falta @Davichobits ? porque justamente el `expect` va a fallar

2023-09-19 19:40 UTC, Davichobits commented on projects/02-data-lovers/tests-read-only/oa/oas-js-datatypes.spec.js
> +      }
A mi me sirvió mucho. Algunas de las descripciones que había generado no estaban cumpliendo con las 100 palabras como mínimo. Este console.error me ayudó para no estar revisando objeto por objeto a ver a cual le faltaba. (En el error que me daba el test no me arrojaba que línea es la producía el error.)

2023-09-19 21:12 UTC, unjust commented on projects/02-data-lovers/src/main.js
> +import data from './data/dataSet.js';
```suggestion
import data from './data/dataset.js';
```

2023-09-20 15:21 UTC, unjust approved these changes

2023-09-20 17:03 UTC, unjust commented on projects/02-data-lovers/README.md
>  #### Testeos de usabilidad
Si! Algunas lo hacen. 
Y no importa si usan los mockups, hay que ver si el producto tal cual hace sentido y los controles son usables.

Creo seria bueno dar mejor fuerza mostrar como hacerlo en los bootcamps.

2023-09-20 17:04 UTC, unjust approved these changes

2023-09-20 21:11 UTC, merged