Prompting learning objectives 1510
Laboratoria/curriculum pull request #1567
Opened 2023-09-11 16:42 UTC by unjust

Addresses #1510

2023-09-11 16:44 UTC, unjust commented on learning-objectives/data.yml
> +    - priming-chatbots
quedamos con estas niveles o collapsar/simplificar un poco?

```
ai-prompt-engineering:
     - giving-instructions
     - few-shot
     ...
```

2023-09-11 16:45 UTC, unjust commented on learning-objectives/intl/es.yml
> +    - title: Prompt Engineering
algunos titulos puede ser mejor en ingles - por ejemplo podemos traducir a `Ingieniera de Prompt`, por ejemplo, pero mucho resultados en espanol aun usa los nombres de terminos en ingles

2023-09-11 17:54 UTC, mfdebian requested changes
Muy pequeños cambios, pero en general se ve bien! :rocket:

2023-09-11 17:54 UTC, mfdebian commented on learning-objectives/intl/es.yml
> +  title: IA Prompting
```suggestion
  title: AI Prompting
```

Lo dejaría como "AI Prompting" sólo para que no esté esa mezcla entre inglés y español, preferiría a que esté o todo en español o todo en inglés, pero la mezcla se siente rara

2023-09-11 17:54 UTC, mfdebian commented on learning-objectives/intl/es.yml
> +    - title: Prompt Engineering
de acuerdo, creo que hoy por hoy hay mucho más contenido sobre los conceptos en inglés

2023-09-11 17:54 UTC, mfdebian commented on learning-objectives/intl/pt.yml
> +  title: IA Prompting
```suggestion
  title: AI Prompting
```

Lo mismo, lo dejaría en inglés para evitar el ingléspañol

2023-09-11 22:39 UTC, ssinuco commented on learning-objectives/data.yml
> +    - priming-chatbots
Llego tarde a la conversacion. Solo comentar que es posible que al final del proyecto una estudiante no use las 4 tecnicas de prompting para generar la data. Tampoco veo que en un PF se pregunte y/o explique todas las tecnicas. Por lo tanto creo que el objetivo de aprendizaje deberia ser mas general algo como "Usar técnicas de prompting como giving instructions, assigning roles, frew shots o priming chatbots para interactuar con LLMS (o AI)".

2023-09-11 23:49 UTC, unjust commented on learning-objectives/data.yml
> +    - priming-chatbots
Puede ser. No tengo un lado fuerte en eso. Creo sería bueno saber cómo los objetivos están visto en el
lado de empleabilidad. Quizá sólo uno sería suficiente y se llama "prompt-engineering" o "prompting" y no tenemos varios OAs.

2023-09-12 17:37 UTC, merunga commented on learning-objectives/data.yml
> +    - priming-chatbots
Personalmente me gusta q sea granular, sin expectativa q marquen todas. 2 o mas de ellas, para mi, ya representan el objetivo de "prompt-engineering" marcado... pero no se si es algo q puedamos hacer ahora.
Igual, lo q proponen de un solo OA, tambien puede ser una opcion para la primera vez.

2023-09-12 17:39 UTC, merunga commented on learning-objectives/intl/es.yml
> +    - title: Prompt Engineering
tb votaria por mantenerlos en ingles

2023-09-12 17:39 UTC, merunga commented on learning-objectives/intl/es.yml
> +ai-prompting/techniques/giving-instructions:
Si colapsamos el OA, habria q meter todas estas referencias al macro OA (sin quitarlas necesariamente de aqui)

2023-09-12 22:22 UTC, Davichobits commented on learning-objectives/intl/es.yml
> +  description: Uso de primer prompt para iniciar una conversación con estructra y estilo particular
```suggestion
  description: Uso de primer prompt para iniciar una conversación con estructura y estilo particular
```

2023-09-13 13:49 UTC, unjust commented
Tengo que mergear esto ahora y solo era una cosita para arreglar que ya hice. ✅ ententido.

2023-09-13 13:50 UTC, merged