Java Agregar proyecto Guess the Number
Laboratoria/curriculum pull request #1639
Opened 2023-11-10 17:47 UTC by cros410

Se crea el proyecto base de Guess the Number con un enfoque para ser desarrollado en Java.

2023-11-15 19:30 UTC, unjust commented on projects/05-guess-the-number/project.yml
> +  - java/access-modifiers (public, private, protected)
actualiza los objetivos. por ejemplo no van a tener espacios en los identificadores.

Puedes probar tu proyecto generando el readme con el create-cohort-project script para ver como parece los objetivos en tu readme final.

2023-11-15 23:33 UTC, cros410 commented
![class-diagram](https://github.com/Laboratoria/curriculum/assets/14276617/b6df26b6-01ed-4f57-bdc8-2c2b07a1b13c)
![guess-the-number-demo](https://github.com/Laboratoria/curriculum/assets/14276617/d7b8d045-9054-464f-8e84-d19d092f1840)
![guess-the-number](https://github.com/Laboratoria/curriculum/assets/14276617/d3bce31b-26c5-4535-a2d8-9170dc1d27fc)
![marcos](https://github.com/Laboratoria/curriculum/assets/14276617/bd7410be-f8cf-491f-a7cf-d4b95319fc88)

2023-11-16 17:29 UTC, unjust reviewed
Solo el comentario a reestablacer el `dist` .
El resto me parece OK.

2023-11-16 17:29 UTC, unjust commented on dist/projects/burger-queen-api-client.json
> -  "parserVersion": "5.1.0",
@cros410 hay que devolver el `dist` como estaba. 
quiza checkout el `dist` de la rama `next` o `main` para reestablecer estes archivos como eran.

2023-11-16 17:29 UTC, unjust commented on projects/05-guess-the-number/README.md
> +![GUESS THE NUMER DEMO](https://firebasestorage.googleapis.com/v0/b/laboratoria-945ea.appspot.com/o/guess-the-number-demo.gif?alt=media)
```suggestion
![GUESS THE NUMBER DEMO](https://firebasestorage.googleapis.com/v0/b/laboratoria-945ea.appspot.com/o/guess-the-number-demo.gif?alt=media)
```

2023-11-16 17:35 UTC, NaraSakamoto requested changes

2023-11-16 17:35 UTC, NaraSakamoto commented on projects/05-guess-the-number/README.pt.md
> +- Concentre-se em adquirir conhecimento ao invés de simplemente "terminar" o projeto.
```suggestion
- Concentre-se em adquirir conhecimento ao invés de simplesmente "terminar" o projeto.
```

2023-11-16 17:35 UTC, NaraSakamoto commented on projects/05-guess-the-number/README.pt.md
> +- Seu aprendizado se desenvolverá à medida que você progrid.
```suggestion
- Seu aprendizado se desenvolverá à medida que você progredir.
```

2023-11-16 17:35 UTC, NaraSakamoto commented on projects/05-guess-the-number/README.pt.md
> +**Atributos estáticos (`static`):**
```suggestion
**Atributos estáticos: **
```

2023-11-16 17:35 UTC, NaraSakamoto commented on projects/05-guess-the-number/README.pt.md
> +Hoje, em out e nov/2023, recomendamos a versão 17 pois é versão mais
```suggestion
Hoje, em out e nov/2023, recomendamos a versão 21 pois é versão mais
```

2023-11-16 17:35 UTC, NaraSakamoto commented on projects/05-guess-the-number/README.md
> +  Hoy, en octubre y noviembre de 2023, recomendamos la versión 17,
```suggestion
  Hoy, en octubre y noviembre de 2023, recomendamos la versión 21,
```

2023-11-16 17:35 UTC, NaraSakamoto commented on projects/05-guess-the-number/README.pt.md
> +assim você poderá criar os testes unitários.
```suggestion
assim você poderá criar os testes unitários.

Recomendamos que você utilize as bibliotecas presentes no repositório Maven: 
- org.junit.jupiter:junit-jupiter
- org.mockito:mockito-core

```

Acho que podemos deixar indicado quais as bibliotecas. Muitas me perguntam!

----

Creo que podemos indicar qué bibliotecas son. ¡Muchos me preguntan!

2023-11-16 17:35 UTC, NaraSakamoto commented on projects/05-guess-the-number/README.md
> +puedas crear pruebas unitarias.
```suggestion
puedas crear pruebas unitarias.

Le recomendamos que utilice las bibliotecas presentes en el repositorio de Maven:
- org.junit.jupiter:junit-jupiter
- org.mockito:mockito-core

```

Acho que podemos deixar indicado quais as bibliotecas. Muitas me perguntam!

----

Creo que podemos indicar qué bibliotecas son. ¡Muchos me preguntan!

2023-11-16 17:35 UTC, NaraSakamoto commented on projects/05-guess-the-number/README.pt.md
> +(recomendamos usar o Java 20).
```suggestion
(recomendamos usar o Java 21).
```

2023-11-16 20:40 UTC, unjust approved these changes

2023-11-16 21:24 UTC, NaraSakamoto approved these changes
Perfeitooo =]]

2023-11-16 22:06 UTC, merged