Java Fleet Management Software API
Laboratoria/curriculum pull request #1640
Opened 2023-11-10 21:33 UTC by cros410

Se crea el proyecto base de Fleet Management Software API con un enfoque para ser desarrollado en Java.

2023-11-13 17:42 UTC, ssinuco reviewed
@cros410 este PR deberia tener 4 READMES:  dos READMES (español y portugues) para JAVA y dos READMES  (español y portugues) para NodeJS. Te sugiero crear dos carpetas: `project/05-java-fleet-management-api-java` y  `project/05-java-fleet-management-api-nodejs` y cambiar el titulo de cada README como Fleet Management Software API JAVA y Fleet Management Software API NODEJS

@unjust @merunga estan de acuerdo ?

2023-11-13 18:24 UTC, merunga commented
yo propondría lo siguiente: que tengamos 6 archivos, 3 para cada idioma:
- el README q especifica el reto de manera "generica" y linkea a los archivos de los posibles stacks de implementaciion: node y java
- README-java.md
- README-node.md

El nombre y la ubicacion de cada archivo está abierta a discusión.

@ssinuco tu propuesta creo q tiene un problema y es que es complicada de escalar. Por ejemplo, si abrimos la posibilidad de que se implemente ademas en .NET y python, ya tendriamos 8 readmes con una buena parte q es la misma para todos.

2023-11-13 20:22 UTC, NaraSakamoto commented on projects/05-java-fleet-management-api/README.md
> +***
```suggestion
#### [Historia de usuario 1] Cargar información a base de datos

Yo, como desarrolladora, quiero cargar la información almacenada hasta ahora en archivos de texto en una base de datos PostgreSQL, para facilitar su consulta y análisis.


##### Criterios de aceptación

* Desarrollar un script SQL que cargue la información de los archivos de texto en la base de datos.

#### Relaciones

Se debe tener en cuenta el siguiente diagrama para la implemetación de las relaciones entre las tablas

![zach-vessels-utMdPdGDc8M-unsplash](./docs/mer.png)

***
```

2023-11-13 20:35 UTC, NaraSakamoto commented on projects/05-java-fleet-management-api/README.md
> +
@cros410 te enviarei o .jar por Slack! =]

2023-11-13 20:37 UTC, NaraSakamoto commented on projects/05-java-fleet-management-api/README.md
> +***
@cros410 te envierei o mer.png pelo Slack também =]

2023-11-13 20:40 UTC, NaraSakamoto commented on projects/05-java-fleet-management-api/project.yml
> +  - java/spring-framework/servlets
Estou pensando sobre removermos esse conceito. Acho que fica implícito quando usamos Spring, não sei se as estudantes precisariam se aprofundar no conceito. 

---

Estoy pensando en eliminar este concepto. Creo que está implícito cuando usamos Spring, no sé si los estudiantes necesitarían profundizar más en el concepto.

2023-11-13 20:43 UTC, NaraSakamoto commented on projects/05-java-fleet-management-api/project.yml
> +  - postgres/indexes
O mesmo pensamento do comentário anterior... 

-----

Lo mismo que el comentario anterior...

2023-11-16 01:52 UTC, unjust commented
> yo propondría lo siguiente: que tengamos 6 archivos, 3 para cada idioma:
> 
> * el README q especifica el reto de manera "generica" y linkea a los archivos de los posibles stacks de implementaciion: node y java
> * README-java.md
> * README-node.md
> 
> El nombre y la ubicacion de cada archivo está abierta a discusión.
> 
> @ssinuco tu propuesta creo q tiene un problema y es que es complicada de escalar. Por ejemplo, si abrimos la posibilidad de que se implemente ademas en .NET y python, ya tendriamos 8 readmes con una buena parte q es la misma para todos.
> 
> @unjust ?

Diria que usamos un archivo `docs/` para los README's extra, entonces solo seria el `README.md` y `README.pt.md` generica al raiz del proyecto que linkean a los `docs/README-java.md` `docs/README-java.pt.md` etc

Un efecto de tener todo los stacks compartido en un proyecto es que van a tener OAs de java y node en el README (porque comparten project.yml) y tambien en el project feedback.

2023-11-16 17:34 UTC, unjust commented on dist/projects/burger-queen-api-client.json
> +  "parserVersion": "5.2.0",
mismo comentario que hay que reestablecer `dist` a lo que tiene `main` o `next`

2023-11-16 17:34 UTC, unjust commented on projects/05-fleet-management-api-java/project.yml
> +  - object-oriented-programming/classes
si es todo de OOP puede solo tener
`- object-oriented-programming` y va a agregar todo

el mismo con `- java`

2023-11-16 18:05 UTC, NaraSakamoto requested changes

2023-11-16 18:05 UTC, NaraSakamoto commented on projects/05-fleet-management-api-java/README.md
> +### [Historia de usuario 4] Endpoint exportación a Excel
```suggestion
### [Historia de usuario 6] Endpoint exportación a Excel
```

Esta seria a História de Usuário 6? Ou devemos remover esta história e considerar a 5 como Hacker Edition? 
@merunga @ssinuco @cros410 @unjust 


----

¿Sería esta la Historia de usuario 6? ¿O deberíamos eliminar esta historia y considerar la 5 como Hacker Edition?

2023-11-16 18:05 UTC, NaraSakamoto commented on projects/05-fleet-management-api-java/README.pt.md
> +### [Historia de usuario 4] Endpoint exportação Excel
```suggestion
### [Historia de usuario 6] Endpoint exportação Excel
```

2023-11-21 13:27 UTC, cros410 commented on projects/05-fleet-management-api-java/README.pt.md
> +respostas sejam mais fáceis de manejar.
Cuando hagamos el cambio de la data para que puedan haber mayor cantidad de trayectorias por taxi me parece que si aplicaría la paginación 
***
Quando alteramos os dados para que haja mais trajetórias por táxi, parece-me que a paginação se aplicaria.

2023-11-21 13:31 UTC, cros410 commented on projects/05-java-fleet-management-api/project.yml
> +  - java/spring-framework/servlets
De esa lista yo solo quitaría servlets porque ya es muy abstracto, pero los demás me parece importante que sepan por lo menos de forma conceptual los componentes de spring y no solo a usarlo de frente, más que nada para se entienda el patrón o arquitectura que usa por defecto spring y lo vean como "buena práctica"

***

Dessa lista, eu só retiraria os servlets porque já são muito abstratos, mas acho importante que os outros conheçam, pelo menos conceitualmente, os componentes do Spring e não apenas os utilizem de antemão. Mais do que qualquer outra coisa, é preciso entender o padrão ou a arquitetura que o Spring utiliza por padrão e encará-lo como uma "boa prática".

2023-11-21 15:06 UTC, cros410 commented on projects/05-java-fleet-management-api/project.yml
> +  - db/indexes-constraints
Coincido, pero podemos dejar los siguientes 
 
```yml
- sql/tables
- db/modeling
- db/connection
- db/indexes-constraints
- postgres/data-types
```

`sql/tables`: Crear las tablas para cargar
`db/modeling`: Identificar que campos debe tener cada tabla
`db/connection`: Conectarse desde un cliente para ver la BD
`db/indexes-constraints`: Agregar las relaciones y caracteristicas ( PF, PK )
`postgres/data-types`: Identificar la diferencia de los tipos de datos con los de Java

***
Concordo, mas podemos deixar o seguinte

`sql/tables`: Criar tabelas para carregar
`db/modeling`: Identificar quais campos cada tabela deve ter
`db/connection`: Conectar-se a partir de um cliente para visualizar o banco de dados
`db/indexes-constraints`: Adicionar as relações e características (PF, PK)
`postgres/data-types`: Identificar a diferença entre tipos de dados e tipos de dados Java.

2023-11-21 15:59 UTC, NaraSakamoto commented on projects/05-java-fleet-management-api/project.yml
> +  - java/spring-framework/servlets
Eu falava sobre servlet mesmo!

2023-11-21 16:01 UTC, NaraSakamoto commented on projects/05-fleet-management-api-java/README.pt.md
> +respostas sejam mais fáceis de manejar.
A história que a paginação não se aplica é a de mostrar a última localização somente. As demais a paginação continua sendo necessária. 

----

El User Story al que no se aplica la paginación es para mostrar solo la última ubicación. Por lo demás, la paginación sigue siendo necesaria.

2023-11-22 18:08 UTC, merunga approved these changes
Me encanta! Gracias @cros410

2023-11-22 18:08 UTC, merunga commented on projects/05-fleet-management-api/docs/README-java.pt.md
> -
Agregar al stack de tecnologias
- despues de JUnit Mockito
- despues de SpringBootTest, MockMVC

2023-11-24 20:58 UTC, NaraSakamoto approved these changes

2023-11-24 20:58 UTC, NaraSakamoto commented on projects/05-fleet-management-api/docs/README.extension.pt.md
> +configurar um banco de dados com as tabelas criadas até o momento.
Que ótima solução! Eu não havia pensado nisso mesmo! Legaal! Gostei muito! <3

2023-11-24 20:58 UTC, NaraSakamoto commented on projects/05-fleet-management-api/docs/README.extension.pt.md
> +* O PostgreSQL está instalado localmente em seu computador.
```suggestion
* O PostgreSQL deve estar instalado localmente em seu computador.
```

2023-11-24 20:58 UTC, NaraSakamoto commented on projects/05-fleet-management-api/docs/README.extension.pt.md
> +* Foi criado um banco de dados local com as tabelas _trajectories_ e _taxis_.
```suggestion
* Deve ter sido criado um banco de dados local com as tabelas _trajectories_ e _taxis_.
```

2023-11-24 20:58 UTC, NaraSakamoto commented on projects/05-fleet-management-api/docs/README.extension.pt.md
> +* O código do seu projeto foi modificado para se conectar ao banco
```suggestion
* O código do seu projeto deve ter sido modificado para se conectar ao banco
```

2023-12-05 16:55 UTC, cros410 commented on projects/05-java-fleet-management-api/project.yml
> +  - postgres/indexes
Issue para revisarlo [1663](https://github.com/Laboratoria/curriculum/issues/1663)

2023-12-05 16:56 UTC, cros410 commented on projects/05-java-fleet-management-api/project.yml
> +  - java/spring-framework/servlets
Issue para revisarlo [1663](https://github.com/Laboratoria/curriculum/issues/1663)

2023-12-05 16:56 UTC, cros410 commented on projects/05-java-fleet-management-api/project.yml
> +  - db/indexes-constraints
Issue para revisarlo [1663](https://github.com/Laboratoria/curriculum/issues/1663)

2023-12-21 19:04 UTC, unjust commented on projects/05-fleet-management-api/README.pt.md
> +contemplados em nossa grade curricular.
## 3. Objetivos de aprendizagem

> ℹ️ Esta seção será automaticamente gerada no idioma pertinente, a partir dos
> objetivos de aprendizagem declarados em [`project.yml`](./project.yml), ao
> criar o repositório do projeto para uma coorte em particular usando
> [`./scripts/create-cohort-project.js`](../../scripts#create-cohort-project-coaches).
>
> Aqui você pode ver uma [lista de todos os objetivos de aprendizagem](../../learning-objectives/data.yml)
> cobertos em nosso currículo.

2023-12-21 19:05 UTC, unjust commented on projects/05-fleet-management-api/README.pt.md
> +contemplados em nossa grade curricular.
```suggestion
## 3. Objetivos de aprendizagem

> ℹ️ Esta seção será automaticamente gerada no idioma pertinente, a partir dos
> objetivos de aprendizagem declarados em [`project.yml`](./project.yml), ao
> criar o repositório do projeto para uma coorte em particular usando
> [`./scripts/create-cohort-project.js`](../../scripts#create-cohort-project-coaches).
>
> Aqui você pode ver uma [lista de todos os objetivos de aprendizagem](../../learning-objectives/data.yml)
> cobertos em nosso currículo.
```

2023-12-21 19:17 UTC, unjust commented on projects/05-fleet-management-api/README.pt.md
> +* [NodeJs](./docs/README-node.pt.md#stack-de-tecnologías)
el create-cohort-project elige la idioma correcta y renombra las archivos `pt.md` a solo `.md`

```suggestion
* [Java](./docs/README-java.md#stack-de-tecnologías)
* [NodeJs](./docs/README-node.md#stack-de-tecnologías)
```

2023-12-21 19:17 UTC, unjust commented on projects/05-fleet-management-api/README.pt.md
> +trabalhar nas [funcionalidades opcionais](./docs/README.extension.pt.md)
```suggestion
trabalhar nas [funcionalidades opcionais](./docs/README.extension.md)
```

2023-12-21 19:33 UTC, unjust approved these changes

2023-12-21 19:33 UTC, merged