Cambio a lenguaje no estricto al momento de solicitar las pruebas OAs…
Laboratoria/curriculum pull request #1669
Opened 2023-12-11 21:17 UTC by Davichobits

… y e2e

Este PR es en respuesta al issue #1638

2023-12-11 21:38 UTC, unjust requested changes
Hay que cambiar el README de "Dataverse", Dataverse Chat mas tarde.

2023-12-20 22:07 UTC, diegovelezg commented on projects/01-text-analyzer/README.md
>  Antes de agendar tu Project Feedback con un coach, asegúrate que tu proyecto:
- con tu coach (y nos evitamos el género)
- asegúrate de que

2023-12-21 14:05 UTC, marianaLz submitted a review, later dismissed

2023-12-21 14:05 UTC, marianaLz commented on projects/01-text-analyzer/README.md
> +  - [ ] Pasan la mayoría de las pruebas unitarias.
cuánto es "la mayoría"?

2023-12-21 14:05 UTC, marianaLz commented on projects/01-text-analyzer/README.md
> +las más importantes para tu proyecto.
👍🏽

2023-12-21 17:59 UTC, unjust commented on projects/01-text-analyzer/README.md
> +  - [ ] Pasan la mayoría de las pruebas unitarias.
Si pense el mismo y por eso solo quita el "todas" para que quedamos con `Pasan las pruebas unitarias.`
De ahi debe tener un conversacion en su OH y su PF si no pasan todos y porque.

2023-12-21 20:26 UTC, marianaLz commented on projects/01-text-analyzer/README.md
> +  - [ ] Pasan la mayoría de las pruebas unitarias.
súper

2023-12-21 20:50 UTC, unjust commented on projects/01-text-analyzer/README.md
>  Antes de agendar tu Project Feedback con un coach, asegúrate que tu proyecto:
```suggestion
Antes de agendar tu Project Feedback con tu coach, asegúrate de que tu proyecto:
```

2024-01-08 15:48 UTC, unjust commented
Move to #1695

2024-01-08 15:48 UTC, closed without merging