Adding translation hitos in dataverse chat
Laboratoria/curriculum pull request #1727
Opened 2024-02-01 17:28 UTC by moniyama

Updates:
- README: change slack channel to pt & add hitos topic
- add files `0x-milestones.pt.md` in /docs directory with translations 

CC @myakiju

#1723

2024-02-08 16:43 UTC, unjust requested changes
Gracias por eso @moniyama 

Deje un comentario y tambien puedes corregir los errores de `mdlint`
https://github.com/Laboratoria/curriculum/actions/runs/7832921458/job/21372710326?pr=1727

si correws `npm run mdlint` localmente va a ver lo mismo errores.

2024-02-08 16:43 UTC, unjust commented on projects/03-dataverse-chat/README.pt.md
> +* [Marco 5](./docs/05-milestone.pt.md)
No necesitamos la extension `pt` en los links. 
Si hace una prueba de `create-cohort-project` los extensiones cambian y solo queda los de portugues.
```suggestion
* [Marco 1](./docs/01-milestone.md)
* [Marco 2](./docs/02-milestone.md)
* [Marco 3](./docs/03-milestone.md)
* [Marco 4](./docs/04-milestone.md)
* [Marco 5](./docs/05-milestone.md)

```

2024-02-09 19:30 UTC, moniyama commented
corrigido @unjust 

gracias!

2024-02-14 16:58 UTC, unjust approved these changes

2024-02-14 16:58 UTC, merged