docs: :bricks: Add django rest-framework oas
Laboratoria/curriculum pull request #1728
Opened 2024-02-01 18:03 UTC by reloadercf

2024-02-02 14:38 UTC, davidgranados commented on learning-objectives/data.yml
> +      - order_by
Esto es del ORM de django no de django rest-framework

2024-02-02 17:20 UTC, unjust requested changes

2024-02-02 17:20 UTC, unjust commented on learning-objectives/intl/es.yml
> +    title: APPS
APPS son mayuscula por algun razon?

2024-02-02 17:20 UTC, unjust commented on learning-objectives/intl/es.yml
> +        url: https://docs.djangoproject.com/en/5.0/ref/databases/#postgresql-notes
Usamos `psycopg2` en Flask también. 
Pero tengo la duda si debemos aggregarlo como OA porque es algo en particular de Postgres (si no usas postgres en el proyecto no tiene que usar psycopg2) y tenemos OAs de Postgres aparte. 
Seria como poniendo el Node driver de MongoDB como objetivo de aprendizaje de BQ API.
Estoy revisando los [OAs de Java](https://github.com/Laboratoria/curriculum/blob/main/learning-objectives/data.yml#L151) para ver si ellos tienen algo similar pero no veo

2024-02-02 17:20 UTC, unjust commented on learning-objectives/intl/es.yml
> +        url: https://docs.djangoproject.com/en/5.0/ref/class-based-views/base/
quiza  `python/django/views/base-view` o solo `python/django/views`, `views/view` me parece raro

2024-02-02 17:20 UTC, unjust commented on learning-objectives/intl/es.yml
> +  python/django/views/testing:
quiza fue un error `python/django/views/testing` que tiene views
quieres `python/django/testing/views`
o solo usamos `python/django/testing`

2024-02-02 17:20 UTC, unjust commented on learning-objectives/intl/es.yml
> +  python/django/views/routes:
`python/django/routes/path:` ?

2024-02-02 17:20 UTC, unjust commented on learning-objectives/intl/es.yml
> +    links:
pondria `python/django/rest-framework` entonces (views es un error de copy pega?) y
`python/django/rest-framework/serializers`
`python/django/rest-framework/filtering`
`python/django/rest-framework/pagination` etc como OAs abajo de `rest-framework`.
Tiene sentido?

2024-02-02 17:25 UTC, icarito commented on learning-objectives/intl/es.yml
> +        url: https://docs.djangoproject.com/en/5.0/ref/databases/#postgresql-notes
Concuerdo que no debemos colocar detalles de implementación en los OA, usar Postrgres ya es suficiente detalle, podrían usar SQLAlchemy también, por ejemplo, pero no lo colocaría como OA... verdad?

2024-02-02 18:16 UTC, reloadercf commented on learning-objectives/intl/es.yml
> +        url: https://docs.djangoproject.com/en/5.0/ref/databases/#postgresql-notes
Por defecto django trabaja con [SQLite](https://www.sqlite.org/) pero mas de un requerimiento de las historias de usuario proponen que se trabaje con Postgres por eso me imaginaba que podría incluirse la conexión como OA pero leyéndoles @unjust @icarito me hace sentido lo que mencionan.

2024-02-06 00:00 UTC, unjust requested changes

2024-02-06 00:00 UTC, unjust commented on learning-objectives/intl/es.yml
> +        url: https://www.django-rest-framework.org/api-guide/generic-views/#genericapiview
estos deberia ser OAs individuales? Me parece muchos links para solo `Rest Framework`

2024-02-06 18:57 UTC, unjust requested changes

2024-02-06 18:57 UTC, unjust commented on learning-objectives/data.yml
> +      - primaryKey
```suggestion
      - foreign-key
      - primary-key
```

2024-02-06 18:57 UTC, unjust commented on learning-objectives/data.yml
> +      - query_params
```suggestion
      - query-params
```

2024-02-06 18:57 UTC, unjust commented on learning-objectives/data.yml
> +      - APIView
```suggestion
      - apiview
```

2024-02-06 18:57 UTC, unjust commented on learning-objectives/intl/es.yml
> +  python/django/setup/apps:
```suggestion
  python/django/setup/app:
```

2024-02-06 18:57 UTC, unjust commented on learning-objectives/data.yml
> +      - apps
```suggestion
      - app
```

2024-02-06 18:57 UTC, unjust commented on learning-objectives/intl/es.yml
> +
```suggestion
```

2024-02-06 18:57 UTC, unjust commented on learning-objectives/data.yml
> +      - primaryKey
borra primary-key si no vamos a tenerlo como OA

2024-02-06 18:57 UTC, unjust commented on learning-objectives/intl/es.yml
> +
```suggestion
```

2024-02-07 17:00 UTC, merged