Separated README for Python and Java
Laboratoria/curriculum pull request #1730
Opened 2024-02-02 21:58 UTC by icarito

Missing PT and probably better references.

2024-02-05 19:05 UTC, unjust commented on projects/05-guess-the-number/README.md
> -## 2. Preámbulo
Es posible que el main README necesita un preambulo. Puede validarlo si en tu rama corres `npm run validate` y ver si el parser sale sin errores.

2024-02-05 19:24 UTC, unjust requested changes

2024-02-05 19:24 UTC, unjust commented on projects/05-guess-the-number/README.md
> +## 2. Resumen del Proyecto
Quiza moveria eso antes de "Consideraciones Generales"

2024-02-05 19:24 UTC, unjust commented on projects/05-guess-the-number/README.md
> -## 2. Preámbulo
Es posible que el main README necesita un preambulo. Puede validarlo si en tu rama corres `npm run validate` y ver si el parser sale sin errores.

2024-02-05 19:24 UTC, unjust commented on projects/05-guess-the-number/README.md
> -## 5. Consideraciones Generales
que raro que habia 2 "consideraciones generales" en el readme anterior

2024-02-05 19:24 UTC, unjust commented on projects/05-guess-the-number/README.md
>  No trabajes como si fueras una fábrica haciendo una clase toda y luego otra.
Sin el contexto de Hitos, esta parte de "No trabajes como si fueras..." creo esta un poco en el aire. Quiza movemos este parte en cada markdown que tiene los hitos (seria duplicado en cada una)

2024-02-05 19:24 UTC, unjust commented on projects/05-guess-the-number/README.md
>  No trabajes como si fueras una fábrica haciendo una clase toda y luego otra.
Y si movimos, nombrar `4. Estrategia...` tiene sentido, o quiza `Lenguajes d eImplementacion` ?

2024-02-05 19:24 UTC, unjust commented on projects/05-guess-the-number/docs/README-java.md
> +- Duración del proyecto: Se estima que este proyecto tomará de 1 a 2 sprints.
Duracion es repetido de las consideraciones en el readme original. Eliminamos?

Quiza este puede ser `Consideracions Generales de Java`

2024-02-05 19:24 UTC, unjust commented on projects/05-guess-the-number/docs/README-java.md
> +  Se mostrará una lista de todas las tentativas de la jugadora ganadora.
QUiza esta parte, porque es generica, podemos mover en el parte de README general, tipo `funcionalidades`

2024-02-05 19:24 UTC, unjust commented on projects/05-guess-the-number/docs/README-python.md
> +
Los hitos puede seguir de formato de los hitos de java

```

### 4.1 Hito 1 - Crear el entorno de desarrollo
### 4.2 Crear un script de Python
### 4.3 Hito 3 - Iniciando el juego "En este hito, puedes crear el juego para un solo jugador..."
### 4.4 Hito 4 - Agregando más jugadoras "En este hito, puedes agregar otra jugadora al juego."
### 4.5 Hito 5 - Creación de pruebas unitarias
### 4.6 Hito 6 - Hito 8 (Edición Hacker) - Creación de una "inteligencia" para jugar contra la computadora
```
Quiza `### 4.4 Mejorar el juego` puede quedar como asi , solo sacaria 4. los tests en su propio hito porque no es "Opcional" y 1 "Lleva un registro de las suposiciones de la jugadora y del ordenador. Cuando el juego termine, muestra todas las suposiciones que hizo la jugadora ganadora." porque esos sonparte de juego integral.

Al final podemos añadir un opcion de "Extension Opcional" con clases para ellas que necesita un paso antes de fleet management si van con un ORM.

2024-02-07 16:24 UTC, icarito commented on projects/05-guess-the-number/README.md
> -## 2. Preámbulo
Al menos el parser no lo requiere. Parece raro que el preámbulo esté antes de algunas consideraciones generales pero es consistente porque habla del lenguaje en cuestión...

2024-02-07 17:02 UTC, icarito commented on projects/05-guess-the-number/README.md
> +## 2. Resumen del Proyecto
De acuerdo

2024-02-07 17:03 UTC, icarito commented on projects/05-guess-the-number/README.md
> -## 5. Consideraciones Generales
Si... queda mejor en dos documentos :shrug:

2024-02-07 17:05 UTC, icarito commented on projects/05-guess-the-number/README.md
>  No trabajes como si fueras una fábrica haciendo una clase toda y luego otra.
*A decir verdad*, esta sección no me hace nada de sentido en el contexto de este proyecto. Prefiero dejarla en el mundo Java. La redacción es confusa y no creo que sea un aporte para Python.

2024-02-07 17:12 UTC, icarito commented on projects/05-guess-the-number/docs/README-java.md
> +- Duración del proyecto: Se estima que este proyecto tomará de 1 a 2 sprints.
Pienso que esto deberíamos dejarlo a criterio de quien esté a cargo de Java. En todo caso, no veo problema en repetir la duración, pero es verdad, yo simplificaría las consideraciones en una sola.

2024-02-07 17:40 UTC, icarito commented on projects/05-guess-the-number/docs/README-python.md
> +
Okey implementé ambos hitos propuestos en el próximo commit.

2024-02-07 17:47 UTC, icarito commented on projects/05-guess-the-number/docs/README-java.md
> +  Se mostrará una lista de todas las tentativas de la jugadora ganadora.
Pienso que no está mal ser redundantes aquí. El README general ya tiene criterios de aceptación que son similares a esta sección.

2024-02-07 17:48 UTC, icarito commented on projects/05-guess-the-number/docs/README-python.md
> +
Podemos revisar las secciones nuevas 4.5 y 4.6 - creo que el resto está OK

2024-02-07 19:24 UTC, icarito commented on projects/05-guess-the-number/docs/README-python.md
> +
:scissors:

2024-02-07 19:31 UTC, icarito commented on projects/05-guess-the-number/README.md
>  ### **Criterios de Aceptación Mínimos del Proyecto**
Done

2024-02-07 22:07 UTC, icarito commented
Bien aquí un primer draft de la traducción a PT final! @unjust

2024-02-08 14:11 UTC, merged