added guide IA
Laboratoria/curriculum pull request #1733
Opened 2024-02-07 01:52 UTC by jmontes50

Añado la guía de IA. Se agradece el feedback.

2024-02-07 16:09 UTC, marianaLz commented on guides/guide-ia/README.md
> +### Crea ejemplos relevantes para tu situación especifica
en el Preview se ven los ###, no lo marca como h3

2024-02-07 16:09 UTC, marianaLz commented on guides/guide-ia/README.md
> +### Solicitar una Revisión de Código a través de IA
en el Preview se ven los ###, no lo marca como h3

2024-02-08 19:38 UTC, unjust reviewed
Muy bien. Algunas commentarios de formato y no agregas los lint configs. Me avisas si necesesitas ayuda con el mdlint.

2024-02-08 19:38 UTC, unjust commented on guides/guide-ia/.markdownlint.json
> +{
quiza este es por tu propio linter plugin, puedes agregar a un gitignore.

2024-02-08 19:38 UTC, unjust commented on guides/guide-ia/.mdlintrc
> +{
igual `.gitignore`

2024-02-08 19:38 UTC, unjust commented on guides/guide-ia/README.md
> +**La respuesta está en aprovechar un asistente con inteligencia artificial!.**
```suggestion
**La respuesta está en aprovechar un asistente con inteligencia artificial.**
```
un `.` o un `!` no los dos ;-)

2024-02-08 19:38 UTC, unjust commented on guides/guide-ia/README.md
> +1. **Comprensión de Código Facilitada:**
Con los numeros me parece que esta en un orden o prioridad. Queremos priorizar estos (como tipo ayuda en errores mas prioridad) o queremos solo presentar una lista sin orden.

Tambien recomiendo que solo el primer palabra esta en mayuscula ejemplo

`Comprensión de código facilitada:`

2024-02-08 19:38 UTC, unjust commented on guides/guide-ia/README.md
> +### Utilízalas para Reducir la Sobrecarga de Información
tambien creo prodemos solo poner el primero en mayuscula

2024-02-08 19:38 UTC, unjust commented on guides/guide-ia/README.md
> +- **Inicia con Independencia:**
aqui tambien los frase puede solo empezar con mayuscual

```suggestion
- **Inicia con independencia:**
```

2024-02-08 19:40 UTC, unjust commented
Y cuando tenemos una version final, agrega el version en portugues con IA por favor!

2024-02-15 19:56 UTC, marianaLz commented
> Y cuando tenemos una version final, agrega el version en portugues con IA por favor!

apoyo!

2024-02-21 21:12 UTC, jmontes50 commented on guides/guide-ia/.markdownlint.json
> +{
removido, gracias!

2024-02-21 21:13 UTC, jmontes50 commented on guides/guide-ia/.mdlintrc
> +{
removido, gracias

2024-02-21 21:13 UTC, jmontes50 commented on guides/guide-ia/README.md
> +**La respuesta está en aprovechar un asistente con inteligencia artificial!.**
done : )

2024-02-21 21:13 UTC, jmontes50 commented on guides/guide-ia/README.md
> +1. **Comprensión de Código Facilitada:**
cambiado a lista, no tiene un orden o prioridad, gracias

2024-02-21 21:13 UTC, jmontes50 commented on guides/guide-ia/README.md
> +- **Inicia con Independencia:**
corregidos todos los que estaban de esa manera

2024-02-21 21:14 UTC, jmontes50 commented on guides/guide-ia/README.md
> +### Utilízalas para Reducir la Sobrecarga de Información
corregido!

2024-02-21 21:14 UTC, jmontes50 commented on guides/guide-ia/README.md
> +### Solicitar una Revisión de Código a través de IA
corregido

2024-02-22 20:04 UTC, unjust commented
@jmontes50 este sigue en Draft.
Crees que podemos cambiar eso a Draft de un PR de verdad para recibir feedback y aprobacion?

2024-02-22 22:31 UTC, jmontes50 commented
> @jmontes50 este sigue en Draft. Crees que podemos cambiar eso a Draft de un PR de verdad para recibir feedback y aprobacion?

@unjust Listo, a la espera de review!, gracias

2024-02-29 21:15 UTC, unjust requested changes

2024-02-29 21:15 UTC, unjust commented on guides/guide-ia/README.md
El directorio se llama `guides/` entonces puede omitir `guide` de titulo de archivo y darlo un nombre en ingles, tipo `using-artificial-intelligence` or `learning-with-ai`

2024-02-29 22:20 UTC, jmontes50 commented on guides/guide-ia/README.md
Cambiado a `learning-with-ai` gracias @unjust , creo que con eso ya va!!

2024-03-01 17:48 UTC, unjust approved these changes

2024-03-01 17:49 UTC, merged