Docs: Add README to detail features of the 'Guess The Number' project in C#
Laboratoria/curriculum pull request #1759
Opened 2024-02-27 02:30 UTC by JuanCarlosHM

Hola equipo,

Agregue el readme del proyecto "Guess the Number" en C#. 

El README incluye: 
- Un preámbulo que introduce la relevancia de C# en la programación moderna.
- Consideraciones generales para una experiencia de aprendizaje efectiva.
- Requisitos previos necesarios para comenzar con el proyecto.
- Una guía paso a paso dividida en hitos, desde la configuración del entorno de desarrollo hasta la implementación de pruebas unitarias.
- Recursos recomendados y enlaces a tutoriales externos para apoyar el aprendizaje y desarrollo del proyecto.

Agradecería cualquier feedback o sugerencias de mejora.

Saludos

#1721

2024-02-27 15:18 UTC, unjust reviewed
Algunas comentarios de estructura. 
Tambien hay que vincular este doc de csharp con el README principal.
Cuando esta lista puedes traducirlo a `pt ` y agrega los objetivos a `proyect.yml` cuando son listos.

2024-02-27 15:18 UTC, unjust commented on projects/05-guess-the-number/docs/README-csharp.md
> +- Video: [inicializar proyecto de consola](https://www.youtube.com/watch?v=axHut2e84fc&t=225s&ab_channel=ProgramadorX)
Este parte "Comenzando" con los prerequisitos y tutorials. me parece mas como parte de "Consideraciones tecnicas" y Hito 1, y repetimos algunas cosas en los dos lugares. No se si hace falta tener esta seccion extra.

2024-02-27 15:18 UTC, unjust commented on projects/05-guess-the-number/docs/README-csharp.md
> +## 1. Preámbulo
Desde aqui abajo esta repetida el contenido.

2024-02-27 15:18 UTC, unjust commented on projects/05-guess-the-number/docs/README-csharp.md
> +
Ojo que estamos saltando niveles de encabezados aqui. Me parece que los Hitos debe ser `###` Y los de abajo `####`

2024-02-27 15:21 UTC, unjust commented on projects/05-guess-the-number/docs/README-csharp.md
> +- **Conocimientos Previos**: Aunque este proyecto está dirigido a principiantes en C#, se recomienda tener una comprensión básica de conceptos de programación como variables, bucles y condiciones. Es
Un poco picky pero prefiero solo un mayuscula como
```suggestion
- **Conocimientos previos**: Aunque este proyecto está dirigido a principiantes en C#, se recomienda tener una comprensión básica de conceptos de programación como variables, bucles y condiciones. Esto facilitará el seguimiento de las explicaciones y la implementación del juego.
```

2024-02-27 15:21 UTC, unjust commented on projects/05-guess-the-number/docs/README-csharp.md
> +- **Estructura del Proyecto**: El proyecto "Adivina el Número" se organiza en una estructura de proyecto simple, con una clase principal que contiene el flujo lógico del juego. Familiarizarte con la
igual una mayuscula aqui 
```suggestion
- **Estructura del proyecto**: El proyecto "Adivina el Número" se organiza en una estructura de proyecto simple, con una clase principal que contiene el flujo lógico del juego. Familiarizarte con la estructura del proyecto te ayudará a entender mejor cómo funciona el código y cómo puedes expandirlo o modificarlo.
```

2024-02-27 20:05 UTC, JuanCarlosHM commented on projects/05-guess-the-number/docs/README-csharp.md
> +- Video: [inicializar proyecto de consola](https://www.youtube.com/watch?v=axHut2e84fc&t=225s&ab_channel=ProgramadorX)
Corregidos ambos puntos

2024-02-27 20:05 UTC, JuanCarlosHM commented on projects/05-guess-the-number/docs/README-csharp.md
> +- **Conocimientos Previos**: Aunque este proyecto está dirigido a principiantes en C#, se recomienda tener una comprensión básica de conceptos de programación como variables, bucles y condiciones. Es
Toda la razón, homologo esa parte para que no se vea extraño

2024-02-29 19:31 UTC, unjust commented on projects/05-guess-the-number/docs/README-csharp.md
> +## 1\. Preámbulo
No debe ser necesario poner este `\.` con los headings

No hay en los otros markdowns [por ejemplo lo de python](https://github.com/Laboratoria/curriculum/blob/main/projects/05-guess-the-number/docs/README-python.md?plain=1)

2024-02-29 19:31 UTC, unjust commented on projects/05-guess-the-number/docs/README-csharp.md
> +---
Quita el division `---`

2024-02-29 19:31 UTC, unjust commented on projects/05-guess-the-number/docs/README-csharp.md
> +---
No es necesario el `---`

2024-02-29 19:31 UTC, unjust commented on projects/05-guess-the-number/docs/classDiagramRelation.png
Sube esta diagrama directamente al descipcion o comentario en el PR, y usa el url de github para agregar al proyecto. No es necesario subir el archivo al proyecto.

2024-02-29 22:32 UTC, JuanCarlosHM commented
![classDiagramRelation](https://github.com/Laboratoria/curriculum/assets/16926528/5a4a7568-d07e-4184-aec8-0874d835114a)

2024-02-29 22:33 UTC, JuanCarlosHM commented
![classDiagramRelation](https://github.com/Laboratoria/curriculum/assets/16926528/52bd945d-1060-4c28-be5e-0f9aff194e85)

2024-03-01 16:13 UTC, danilolab requested changes
Dejé algunas sugerencias que permitan una mejor comprensión del texto en portugués. Y también una pequeña sugerencia de reordenamiento de los temas, para darle más claridad a los estudiantes siguiendo los hitos.

2024-03-01 16:13 UTC, danilolab commented on projects/05-guess-the-number/docs/README-csharp.pt.md
> +Refatorar o código do jogo para que a lógica interna do jogo
Refatorar o código do jogo para que sua lógica interna

2024-03-01 16:13 UTC, danilolab commented on projects/05-guess-the-number/docs/README-csharp.pt.md
> +para armazenar as previsões realizadas.
para armazenar as tentativas realizadas.

2024-03-01 16:13 UTC, danilolab commented on projects/05-guess-the-number/docs/README-csharp.pt.md
> +que solicita ao usuário por um número.
que solicita um número ao usuário.

2024-03-01 16:13 UTC, danilolab commented on projects/05-guess-the-number/docs/README-csharp.pt.md
> +  + Manter o nome e o histórico de suposições do jogador.
+ Manter o nome e o histórico de palpites do jogador.

2024-03-01 16:13 UTC, danilolab commented on projects/05-guess-the-number/docs/README-csharp.pt.md
> +Criar uma suíte de testes unitários que cubra os diferentes
Criar uma suíte (conjunto) de testes unitários que cubra os diferentes

2024-03-06 15:37 UTC, unjust commented on projects/05-guess-the-number/README.pt.md
> +- [Versão em C#](./docs/README-csharp.pt.md)
```suggestion
- [Versão em C#](./docs/README-csharp.md)
```

2024-03-06 15:40 UTC, merged