new project.yml propsal
Laboratoria/curriculum pull request #1779
Opened 2024-03-05 17:50 UTC by merunga

Se agrega propuesta de nueva estructura para soportar:
- variantes (aka rutas)
- OAs opcionales
- project tags

2024-03-06 18:19 UTC, unjust reviewed
Interesante. Y si marcamos algunos como variants, pensamos en generar proyectos por cada variant - osea que `create-cohort-project` preguntaria cual variant quiere generar si estas generando un variant? Si pensamos si, tambien tiene la implicacion que cada doc de variant debe seguir un convencion de nombre .

Por ultima hay 2 cosas de curriculum y curriculum parser que seria buena cerrar antes de eso.
https://github.com/Laboratoria/curriculum-parser/pull/86
https://github.com/Laboratoria/curriculum/pull/1681

2024-03-06 18:19 UTC, unjust commented on projects/05-fleet-management-api/project.yml
> +tags:
`level` (`nivel`) seria aqui tambien?

Estaba pensando en `tags` o algo similar que también permite elegir y vincular recursos en el readme que curamos en otro lado.

2024-03-12 18:19 UTC, merunga commented on projects/05-fleet-management-api/project.yml
> +      - db: false
@lupomontero agregué esta opción, no se qué opinas y no se cuán factible es?
el work around es mover esos 2 OAs de la propiedad de root, y copiarlo en cada uno de los otros variants, q me pareció un poco engorroso y verbose

2024-03-27 20:31 UTC, mfdebian requested changes
Díganme qué opinan de esta propuesta :blush:

2024-03-27 20:31 UTC, mfdebian commented on projects/05-fleet-management-api/project.yml
> +          optional: true
me sumo al comentario de que, para agregar la funcionalidad de mostrar o no un OA, no es necesario que sea un objeto que incluya una propiedad `optional`, sino que simplemente puede ser un booleano, es decir:

```suggestion
      - object-oriented-programming: true
```

2024-03-27 20:31 UTC, mfdebian commented on projects/05-fleet-management-api/project.yml
> +          optional: true
```suggestion
      - object-oriented-programming: true
```

2024-03-27 22:45 UTC, merunga commented on projects/05-fleet-management-api/project.yml
> +          optional: true
@mfdebian ojo q los casos son 2 distintos:
- uno es cuando el OA no se debe mostrar
- el segundo es q se debe mostrar pero no es obligatorio conseguirlo para dar el proyecto como terminado

Dicho eso, asumiría q:
```yml
- object-oriented-programming: true
```
tendría el mismo efecto q:
```yml
- object-oriented-programming
```

2024-03-27 22:49 UTC, merunga commented on projects/05-fleet-management-api/project.yml
> +          optional: true
@mfdebian ojo q los casos son 2 distintos:
- uno es cuando el OA no se debe mostrar
- el segundo es q se debe mostrar pero no es obligatorio conseguirlo para dar el proyecto como terminado

Dicho eso, asumiría q:
```yml
- object-oriented-programming: true
```
tendría el mismo efecto q:
```yml
- object-oriented-programming
```

2024-04-01 13:20 UTC, mfdebian commented on projects/05-fleet-management-api/project.yml
> +          optional: true
aaaah okey! se entiende

2024-04-02 14:28 UTC, mfdebian requested changes

2024-04-02 14:28 UTC, mfdebian commented on projects/05-fleet-management-api/project.yml
> +      - django
```suggestion
      - python/django
```

Los OAs deberían seguir escribiéndose como se escriben en los demás proyectos, para saber que esa propiedad corresponde a los OAs de `python`, o si no el parser creerá que ese OA (`django` por sí solo) no existe, y por ende arroja error (`Unknown learning objectives: django.`); Este comportamiento es así porque (quizás con la palabra _django_ no ocurrirá, pero) existen OAs "repetidos", por ejemplo `functions` es tanto un OA _dentro_ del OA `js` como de `csharp`, `php`, `python`, etc... Y algunos incluyen cosas que otros no.

Entonces mejor mantener la convención :blush:

2024-04-26 18:00 UTC, unjust commented
Revisando eso de nuevo con [el PR de `curriculum-parser`](https://github.com/Laboratoria/curriculum-parser/pull/88/files) me gustaria documentemos los cambios que vemos en [este nuevo proyect.yml](https://github.com/Laboratoria/curriculum/blob/0bbd57f86785fc3aa945e6612bd79cbef58f7b39/projects/05-fleet-management-api/project.yml)

`track`: no cambios (web-dev, ux, data...)
`learningObjectives`: no cambios, pero esos son los OAs basicos de proyecto, que van compartir la mayoria en cualquier version de proyecto

nuevos propiedades:
`tags`: un status de proyecto para ayudar con prioridad y display en el sitio (deprecated, hidden, featured)
`variants`: los variantes de proyecto depende en lenguaje o framework (java, node, react, angular, python-flask, python-django)
      - `name`: nombre de variante (python, react, react-typescript seria uno? ) no se si tenemos traducir este nombre como titulo para mostrarlo en interfaz
      - `learningObjectives`: los objetivos nuevos que trae el variante
          - `[name_of_objective]: false` para apagar o omitir un OA de la raiz con este variante
          -  `optional: true` veo 3 casos en los ejemplos 
          1. si un objetivo de [este variante es incluido como opcional](https://github.com/Laboratoria/curriculum/blob/0bbd57f86785fc3aa945e6612bd79cbef58f7b39/projects/05-fleet-management-api/project.yml#L30C7-L31C25), 
          2. [un OA de objetivos de root son opcional](https://github.com/Laboratoria/curriculum-parser/blob/375b5a2de3a6779b0825cd470d3d5b41534d81eb/lib/__tests__/__fixtures__/01-a-project-with-optional-learning-objectives/project.yml) 
          3. [si un objetivo es opcional en el root y el variante](https://github.com/Laboratoria/curriculum-parser/blob/375b5a2de3a6779b0825cd470d3d5b41534d81eb/lib/__tests__/__fixtures__/01-a-project-with-variant-learning-objectives-duplicated/project.yml#L18-L25)

Nota `optional` me imagino siempre sera `true` y no existia `optional: false`

2024-05-21 13:35 UTC, lupomontero commented on projects/05-fleet-management-api/project.yml
> +tags:
@unjust, si no me equivoco, el _nivel_ se infiere del prefijo de la carpeta del proyecto. Por ejemplo, en este proyecto en particular la carpeta es `05-fleet-management-api`, el prefijo es `05-`, y de ahí se infiere el nivel.

2024-06-10 15:40 UTC, lupomontero commented on projects/05-fleet-management-api/project.yml
> +          optional: true
Entiendo que un OA opcional aplicaría cuando dependiendo de la implemetación pueda hacerse el proyecto con o sin la tecnología, herramienta o skill en particular.

2024-06-10 15:43 UTC, lupomontero commented on projects/05-fleet-management-api/project.yml
> +      - db: false
@merunga, en los `project.yml` se podría usar la propiedad `exclude` (booleano) en los objetos de tipo _learning objective_ que queramos excluir de la variante... tienes algún ejemplo de proyecto que necesite este feature?

2024-06-11 17:04 UTC, lupomontero commented on projects/05-fleet-management-api/project.yml
> +      - db: false
@merunga, la versión final de `curriculum-parser` incluye esta opción. He modificado el `project.yml` de `fleet-management-api` para usar este feature como ejemplo en la variante de `python`.

2024-06-11 17:38 UTC, lupomontero approved these changes

2024-06-11 17:40 UTC, mfdebian submitted a review, later dismissed
LFGTM :star:

2024-06-11 20:38 UTC, merunga commented
hola, [actualicé los tags de los proyectos](https://github.com/Laboratoria/curriculum/commit/7e983c0073541093ccfcdb3a15d800f52c820bdc)... estoy pensando q debería haber enviado un PR desde una nueva rama, perdon.

Hay un solo cambio q no se si habria q hacer ahora o no, y es pasar a guess the number a un proyecto de nivel 4 @mfdebian @unjust

2024-06-13 15:52 UTC, lupomontero approved these changes

2024-06-13 15:52 UTC, mfdebian approved these changes
LGTM

2024-06-13 15:54 UTC, merged