Añadida guía de csharp para fleet api management
Laboratoria/curriculum pull request #1782
Opened 2024-03-06 23:31 UTC by jmontes50

He añadido la guía para fleet api, se agradece el feedback! @unjust @JuanCarlosHM @danilolab @marianaLz @GenesisMauries 

He buscado que sea algo guiada pero me comentar como va.

2024-03-07 18:27 UTC, unjust requested changes
Gracias @jmontes50! Algunas correciones pequeñas.

De ahi revisa el checklist en el issue #1722 para los otros partes de proyecto que necesitamos agregar.

2024-03-07 18:27 UTC, unjust commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +### 7. Fluent API ###
Salto de 5 a 7

2024-03-07 18:27 UTC, unjust commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +### 7. Fluent API ###
```suggestion
### 6. Fluent API ###
```

2024-03-07 18:27 UTC, unjust commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +### 9. Ejecutar migraciones ###
```suggestion
### 8. Ejecutar migraciones ###
```

Y la demas de abajo

2024-03-08 16:39 UTC, GenesisMauries commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +y gestión eficiente de datos. Entity Framework y PostgreSQL destacan por su
```suggestion
y gestión eficiente de datos. [Entity Framework](https://learn.microsoft.com/es-es/dotnet/framework/data/adonet/ef/overview) y [PostgreSQL](https://www.postgresql.org/) destacan por su
```

2024-03-08 16:39 UTC, GenesisMauries commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +.NET Core, de Microsoft, es un framework eficiente
```suggestion
[.NET Core](https://dotnet.microsoft.com/es-es/learn/dotnet/what-is-dotnet), de Microsoft, es un framework eficiente
```

2024-03-08 16:39 UTC, GenesisMauries commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +Entity Framework simplifica la conexión a bases de datos al permitir a los devs
```suggestion
[Entity Framework](https://learn.microsoft.com/es-es/dotnet/framework/data/adonet/ef/overview) simplifica la conexión a bases de datos al permitir a los devs
```

2024-03-08 16:39 UTC, GenesisMauries commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +directamente con consultas SQL,
```suggestion
directamente con consultas [SQL](https://aws.amazon.com/es/what-is/sql/),
```

2024-03-08 16:39 UTC, GenesisMauries commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +Asegúrate de tener instalado un entorno de desarrollo, ya sea Visual Studio
```suggestion
Asegúrate de tener instalado un entorno de desarrollo, ya sea [Visual Studio Community](https://visualstudio.microsoft.com/es/vs/community/)
```

2024-03-08 16:39 UTC, GenesisMauries commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +Community Edition o Visual Studio Code, junto con el kit de desarrollo de C#.
```suggestion
Community Edition o [Visual Studio Code](https://code.visualstudio.com/), junto con el kit de desarrollo de C#.
```

2024-03-08 16:39 UTC, GenesisMauries commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +Además, es esencial comprender los conceptos básicos de las APIs (Interfaces de
```suggestion
Además, es esencial comprender los conceptos básicos de las [APIs](https://aws.amazon.com/es/what-is/api/) (Interfaces de
```

2024-03-08 16:39 UTC, GenesisMauries commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +para probar tus rutas y métodos según los hayas desarrollado.
```suggestion
Es fundamental probar tu APIs para asegurarte de que funciona correctamente antes de implementarla
en producción. Aquí es donde entran en juego herramientas como
[Postman](https://www.postman.com/) y 
[Thunder Client](https://www.thunderclient.io/) para probar las rutas y métodos que 
desarrollaste.

Existen varias razones para usar [Postman](https://www.postman.com/)
y [Thunder Client](https://www.thunderclient.io/)  al desarrollar APIs:

- Estas herramientas te permiten simular fácilmente solicitudes HTTP a tu API, evitando la necesidad de escribir código adicional.
- Puedes verificar rápidamente los códigos de estado, encabezados y el cuerpo de las respuestas para identificar errores de manera ágil.
- La capacidad de formatear respuestas JSON y probar diferentes tipos de solicitudes (GET, POST, PUT, DELETE) te permite explorar exhaustivamente la funcionalidad de tu API.
 - Postman y Thunder Client también permiten almacenar y reutilizar solicitudes y respuestas, ahorrando tiempo en tareas repetitivas.
```

2024-03-11 17:15 UTC, unjust requested changes
Deje comentarios 

Tambien hay 2 cosas mas:
1 - en extension.md hay que poner un link de extension-cli.md#csharp [en este parte](https://github.com/Laboratoria/curriculum/blob/d5b8aec07b9436348c5e1eb156926b50f8ab795f/projects/05-fleet-management-api/docs/extension.md?plain=1#L75-L79)
2 - arrgela los [links de imagenes usado en el markdown de la extension](https://github.com/Laboratoria/curriculum/issues/1786) se llama first-10-lines-taxis-txt.png y first-10-lines-9557-txt.png

2024-03-11 17:49 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +y gestión eficiente de datos. Entity Framework y PostgreSQL destacan por su
done! ty

2024-03-11 18:36 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +## Consideraciones generales ##
Corregido, era porque no me dejaba poner C#, lo puse C\# y solucionado, gracias!

2024-03-11 18:36 UTC, jmontes50 commented on projects/05-fleet-management-api/README.pt.md
> +* [C#](./docs/stack-csharp.pt.md)
corregido

2024-03-11 19:01 UTC, unjust reviewed
AUn podemos quitar los `#` a final de headers
Puedes reemplezar los links en los siguientes partes para corregir #1786 
https://github.com/Laboratoria/curriculum/pull/1782/files#diff-479016362133a762641ff55f4b1b20cbf53c44f81b6a643d143eac6117483a3dL52
https://github.com/Laboratoria/curriculum/pull/1782/files#diff-479016362133a762641ff55f4b1b20cbf53c44f81b6a643d143eac6117483a3dR62

2024-03-12 22:03 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +.NET Core, de Microsoft, es un framework eficiente
actualizado!

2024-03-12 22:03 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +Entity Framework simplifica la conexión a bases de datos al permitir a los devs
actualizado!

2024-03-12 22:03 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +directamente con consultas SQL,
actualizado! ty!

2024-03-12 22:03 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +Asegúrate de tener instalado un entorno de desarrollo, ya sea Visual Studio
actualizado! ty!

2024-03-12 22:04 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +Community Edition o Visual Studio Code, junto con el kit de desarrollo de C#.
actualizado! ty!

2024-03-12 22:04 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +Además, es esencial comprender los conceptos básicos de las APIs (Interfaces de
actualizado! ty!

2024-03-12 22:04 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +para probar tus rutas y métodos según los hayas desarrollado.
actualizado! utilice la primera parte para no dar tanta info, ty!

2024-03-12 22:04 UTC, jmontes50 commented on projects/05-fleet-management-api/docs/stack-csharp.md
> +## Stack de tecnologías ##
corregido, gracias!

2024-03-15 15:48 UTC, unjust approved these changes
Gracias @jmontes50 !

2024-03-15 19:24 UTC, unjust approved these changes

2024-03-15 19:25 UTC, merged