Cambios movie challenge sin fw
Laboratoria/curriculum pull request #1789
Opened 2024-03-20 16:49 UTC by MarciaMillanao

Cambios en el Readme de proyecto Movie Challenge, segun [PR](https://github.com/Laboratoria/SAP012-movie-challenge/pull/1#pullrequestreview-1928876804)

@marianaLz @unjust

2024-03-20 18:13 UTC, unjust requested changes
Use este diff para ver los cambios https://www.diffchecker.com/u9ZqFxeP/

Queremos hacer lo mismo cambios en portugues?

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +- Las pruebas unitarias deben cubrir al menos el 90% statements, functions,
Pequeno, pero detalle de requisito de pruebas me parece una consideracion tecnica, y quiza tambien lo de estructura cuand o hablamos de boilerplate abajo.

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +V3 [de la Base de Datos de Películas](https://developer.themoviedb.org/docs/getting-started)
Porque es el mismo link mejor como 

```suggestion
- Para poder usar la [La API V3 de la Base de Datos de Películas]](https://developer.themoviedb.org/docs/getting-started)
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +deberás crear una llave(key) de acceso agregarla a cada petición que hagas al
```suggestion
deberás crear una llave (key) de acceso agregarla a cada petición que hagas al
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +### `scr/components/App.js`
```suggestion
### `src/components/App.js`
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +- La aplicación debe ser una aplicación de una sola página.
Aqui creo debemos presentar que es un SPA y linkear en el readme a la guia

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +Aquí es donde recomendamos implementar su SPA.
```suggestion
Aquí es donde recomendamos implementar su SPA (Single Page Application).
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +aplicación en esta [imagen](https://github.com/Laboratoria/SAP012-movie-challenge/blob/main/docs/movie-detail.png)
Descriimos un poco mas de text link
```suggestion
aplicación en esta [imagen de pagina de detalle](https://github.com/Laboratoria/SAP012-movie-challenge/blob/main/docs/movie-detail.png)
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +y en [este](https://github.com/Laboratoria/SAP012-movie-challenge/blob/main/docs/movie-list.png)
```suggestion
y en [este imagen de lista de peliculas](https://github.com/Laboratoria/SAP012-movie-challenge/blob/main/docs/movie-list.png)
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +#### [Historia de Usuario 1] Lista de Películas**
```suggestion
#### [Historia de Usuario 1] Lista de Películas
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +- El endpoint debe ser utilizado [/discover/movie.](https://developer.themoviedb.org/reference/discover-movie)
```suggestion
- [El endpoint `/discover/movie`](https://developer.themoviedb.org/reference/discover-movie) debe ser utilizado.
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +que permite implementar nuestra aplicación web estática (HTML, CSS y JavaScritp)
```suggestion
que permite implementar nuestra aplicación web estática (HTML, CSS y JavaScript)
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +#### Planear la implemantación de la primera Historia de Usuario
```suggestion
#### Planear la implementación de la primera Historia de Usuario
```

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +
algun recurso de componentes? Podemos pensar en eso...

2024-03-20 18:13 UTC, unjust commented on projects/03-movie-challenge/README.md
> +[Router con JavaScript puro](https://github.com/Laboratoria/curriculum/blob/main/guides/router-spa/README.pt.md)
```suggestion
[Router con JavaScript puro](https://github.com/Laboratoria/curriculum/blob/main/guides/router-spa/README.md)
```

2024-03-20 19:08 UTC, marianaLz commented on projects/03-movie-challenge/README.md
> +# Movie Challenge
sí

2024-03-20 22:05 UTC, MarciaMillanao commented on projects/03-movie-challenge/README.md
> +- Las pruebas unitarias deben cubrir al menos el 90% statements, functions,
Si más abajo hablamos de boilerplate

2024-03-20 22:07 UTC, MarciaMillanao commented on projects/03-movie-challenge/README.md
> +- La aplicación debe ser una aplicación de una sola página.
https://github.com/Laboratoria/curriculum/blob/main/guides/router-spa/README.md 
Esta guía?

2024-03-21 20:05 UTC, unjust approved these changes
Los cambios me parece bien. SI falta algo de traduccion podemos abrir nuevo issue. Gracias @MarciaMillanao !

2024-03-21 20:06 UTC, merged