Create new UXD project
Laboratoria/curriculum pull request #1797
Opened 2024-04-08 22:06 UTC by lisperaza

This new project merges UXploradoras UI + UXploradoras UX

2024-04-10 16:55 UTC, unjust requested changes
Falta un heading standarizado para los Objetivos

Y tambien hay algunos errores de MD lint para corregir que pueden encontrar en este pagina:
https://github.com/Laboratoria/curriculum/pull/1797/checks

son estos (numero de linea es el numero que empieza cada error)
```
> curriculum@8.5.0 mdlint
> mdlint .

/home/runner/work/curriculum/curriculum/projects/02-uxploradoras/README.md
  35:24 no-trailing-punctuation [MD026] Trailing punctuation in heading [Punctuation: ':']
  [12](https://github.com/Laboratoria/curriculum/pull/1797/checks#step:5:13)8:54 no-trailing-spaces [MD009] Trailing spaces [Expected: 0 or 2; Actual: 1]
  161:[13](https://github.com/Laboratoria/curriculum/pull/1797/checks#step:5:14) no-trailing-spaces [MD009] Trailing spaces [Expected: 0 or 2; Actual: 1]
  257:1 ol-prefix [MD029] Ordered list item prefix [Expected: 2; Actual: 3; Style: 1/2/3]
  266 blanks-around-lists [MD032] Lists should be surrounded by blank lines "- Diferenciar claramente que f..."

Summary:
5 issues in 1 file(s)
 - undefined 5
```

2024-04-10 16:55 UTC, unjust commented on projects/02-uxploradoras/README.md
> +### Objetivos de aprendizaje
El proyecto necesita un heading con numero aqui
```suggestion
## 3. Objetivos de aprendizaje
```

Y de ahi poner numeros 4- ... seguidos al siguente headings

2024-04-10 18:32 UTC, lisperaza commented
Listo! ya cambié el heading y los errores de sintaxis.

2024-04-11 03:18 UTC, unjust commented on projects/02-uxploradoras/README.md
> +
Parece que falta otro parte requerido se llama "Resumen de proyecto", similar a 
https://github.com/Laboratoria/curriculum/tree/main/projects/02-uxploradoras-ui#2-resumen-del-proyecto
https://github.com/Laboratoria/curriculum/tree/main/projects/03-uxploradoras-ux

2024-04-11 03:18 UTC, unjust approved these changes

2024-04-11 03:21 UTC, unjust commented on projects/02-uxploradoras/README.md
> +
Parece que falta otro parte requerido se llama "Resumen de proyecto", similar a
https://github.com/Laboratoria/curriculum/tree/main/projects/02-uxploradoras-ui#2-resumen-del-proyecto
https://github.com/Laboratoria/curriculum/tree/main/projects/03-uxploradoras-ux


puedes encontar el error aqui https://github.com/Laboratoria/curriculum/pull/1797/checks
```
<= FAIL: Error parsing projects/02-uxploradoras
No project summary found
└── projects/02-uxploradoras/README.md
```

2024-04-11 20:52 UTC, unjust commented on projects/02-uxploradoras/README.md
> +
Quiza puede robar directamente los resumenes de proyecto anteriors que sirve, tipo:

```suggestion
## 2. Resumen del proyecto

En las plataformas de e-commerce, es crucial que las personas usuarias puedan navegar rápidamente entre el mar de productos que ofrecen. Una buena arquitectura de información permite encontrar lo que buscas y realizar tus compras de forma satisfactoria.

Para este proyecto tu misión será re-diseñar o mejorar la categorización de productos (agrupación), etiquetas (nombres), navegación y formas de búsqueda de un e-commerce con alto volumen de productos. Los supermercados en línea o tiendas departamentales son candidatos ideales para este proyecto, debes elegir uno al cual tú y muchos usuarios tengan fácil acceso, así será más fácil que encuentres participantes para análisis de usabilidad y card-sorting.
```

Y de ahi icrementar los numeros para acomodar este seccion nueva.

2024-04-12 15:13 UTC, unjust commented on projects/02-uxploradoras/README.md
> +## 2. Resumen
```suggestion
## 2. Resumen del proyecto
```

2024-04-12 15:13 UTC, unjust commented on projects/02-uxploradoras/README.md
> +- [2. Resumen](#2-resumen)
```suggestion
- [2. Resumen del proyecto](#2-resumen-del-proyecto)
```

2024-04-12 16:07 UTC, unjust approved these changes

2024-04-12 16:07 UTC, merged